<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Electronics
            [
                'shop_id' => 1,
                'name' => 'Sony WH-1000XM5 Wireless Noise-Canceling Headphones',
                'category' => 'Electronics',
                'price' => 899,
                'original_price' => 1299,
                'discount_percentage' => 31,
                'rating' => 4.9,
                'sold_count' => 3240,
                'stock' => 45,
                'free_shipping' => true,
                'location' => 'Kuala Lumpur',
                'badge' => 'Best Seller',
                'is_featured' => true,
            ],
            [
                'shop_id' => 1,
                'name' => 'MacBook Pro 14" M3 Pro',
                'category' => 'Electronics',
                'price' => 8499,
                'original_price' => 9499,
                'discount_percentage' => 11,
                'rating' => 4.9,
                'sold_count' => 2100,
                'stock' => 12,
                'free_shipping' => true,
                'location' => 'Kuala Lumpur',
                'badge' => 'Official Store',
                'is_featured' => true,
            ],
            [
                'shop_id' => 1,
                'name' => 'Logitech MX Master 3S Wireless Mouse',
                'category' => 'Electronics',
                'price' => 219,
                'original_price' => 299,
                'discount_percentage' => 27,
                'rating' => 4.9,
                'sold_count' => 5600,
                'stock' => 78,
                'free_shipping' => true,
                'location' => 'Kuala Lumpur',
                'badge' => 'Best Seller',
                'is_featured' => false,
            ],
            [
                'shop_id' => 1,
                'name' => 'COSRX Advanced Snail 96 Mucin Power Essence',
                'category' => 'Beauty',
                'price' => 55,
                'original_price' => 79,
                'discount_percentage' => 30,
                'rating' => 4.8,
                'sold_count' => 18900,
                'stock' => 234,
                'free_shipping' => true,
                'location' => 'Shah Alam',
                'badge' => 'Best Seller',
                'is_featured' => false,
            ],

            // Fashion
            [
                'shop_id' => 2,
                'name' => 'Nike Air Max 270 Men\'s Running Shoes',
                'category' => 'Fashion',
                'price' => 389,
                'original_price' => 520,
                'discount_percentage' => 25,
                'rating' => 4.8,
                'sold_count' => 8750,
                'stock' => 92,
                'free_shipping' => true,
                'location' => 'Penang',
                'badge' => 'Flash Deal',
                'is_featured' => true,
            ],
            [
                'shop_id' => 2,
                'name' => 'Adidas Ultraboost 22 Running Shoes',
                'category' => 'Fashion',
                'price' => 349,
                'original_price' => 499,
                'discount_percentage' => 30,
                'rating' => 4.7,
                'sold_count' => 4320,
                'stock' => 65,
                'free_shipping' => true,
                'location' => 'Penang',
                'badge' => null,
                'is_featured' => false,
            ],

            // Home & Living
            [
                'shop_id' => 3,
                'name' => 'Scandinavian Oak Coffee Table with Storage',
                'category' => 'Home & Living',
                'price' => 649,
                'original_price' => 890,
                'discount_percentage' => 27,
                'rating' => 4.7,
                'sold_count' => 1820,
                'stock' => 23,
                'free_shipping' => false,
                'location' => 'Johor Bahru',
                'badge' => 'Voucher',
                'is_featured' => true,
            ],
            [
                'shop_id' => 3,
                'name' => 'Luxury Velvet Throw Pillow Set (4 pcs)',
                'category' => 'Home & Living',
                'price' => 89,
                'original_price' => 129,
                'discount_percentage' => 31,
                'rating' => 4.5,
                'sold_count' => 6700,
                'stock' => 156,
                'free_shipping' => true,
                'location' => 'Johor Bahru',
                'badge' => 'New',
                'is_featured' => false,
            ],
            [
                'shop_id' => 3,
                'name' => 'Minimalist Linen Sofa 3-Seater — Warm Beige',
                'category' => 'Home & Living',
                'price' => 2499,
                'original_price' => 3200,
                'discount_percentage' => 22,
                'rating' => 4.6,
                'sold_count' => 930,
                'stock' => 8,
                'free_shipping' => false,
                'location' => 'Johor Bahru',
                'badge' => null,
                'is_featured' => true,
            ],

            // More Electronics
            [
                'shop_id' => 1,
                'name' => 'Samsung Galaxy S24 Ultra',
                'category' => 'Electronics',
                'price' => 4899,
                'original_price' => 5499,
                'discount_percentage' => 11,
                'rating' => 4.8,
                'sold_count' => 3400,
                'stock' => 34,
                'free_shipping' => true,
                'location' => 'Kuala Lumpur',
                'badge' => 'Official Store',
                'is_featured' => true,
            ],
            [
                'shop_id' => 1,
                'name' => 'iPad Pro 12.9" M2',
                'category' => 'Electronics',
                'price' => 3499,
                'original_price' => 3899,
                'discount_percentage' => 10,
                'rating' => 4.8,
                'sold_count' => 2456,
                'stock' => 28,
                'free_shipping' => true,
                'location' => 'Kuala Lumpur',
                'badge' => 'Best Seller',
                'is_featured' => false,
            ],

            // Beauty
            [
                'shop_id' => 4,
                'name' => 'SK-II Facial Treatment Essence 160ml',
                'category' => 'Beauty',
                'price' => 189,
                'original_price' => 269,
                'discount_percentage' => 30,
                'rating' => 4.9,
                'sold_count' => 5234,
                'stock' => 89,
                'free_shipping' => true,
                'location' => 'Kuala Lumpur',
                'badge' => 'Best Seller',
                'is_featured' => true,
            ],
            [
                'shop_id' => 4,
                'name' => 'MAC Fix+ Setting Spray 100ml',
                'category' => 'Beauty',
                'price' => 45,
                'original_price' => 65,
                'discount_percentage' => 30,
                'rating' => 4.7,
                'sold_count' => 9876,
                'stock' => 234,
                'free_shipping' => true,
                'location' => 'Kuala Lumpur',
                'badge' => null,
                'is_featured' => false,
            ],

            // Books
            [
                'shop_id' => 5,
                'name' => 'Atomic Habits by James Clear (Hardcover)',
                'category' => 'Books',
                'price' => 49,
                'original_price' => 69,
                'discount_percentage' => 29,
                'rating' => 4.9,
                'sold_count' => 12450,
                'stock' => 456,
                'free_shipping' => true,
                'location' => 'Shah Alam',
                'badge' => 'Best Seller',
                'is_featured' => false,
            ],

            // Sports
            [
                'shop_id' => 5,
                'name' => 'Yoga Mat Premium Non-Slip TPE 6mm',
                'category' => 'Sports',
                'price' => 89,
                'original_price' => 129,
                'discount_percentage' => 31,
                'rating' => 4.6,
                'sold_count' => 7234,
                'stock' => 145,
                'free_shipping' => true,
                'location' => 'Shah Alam',
                'badge' => 'New',
                'is_featured' => false,
            ],

            // Automotive
            [
                'shop_id' => 1,
                'name' => 'Car Phone Mount Dashboard Windshield',
                'category' => 'Automotive',
                'price' => 25,
                'original_price' => 45,
                'discount_percentage' => 44,
                'rating' => 4.8,
                'sold_count' => 23456,
                'stock' => 567,
                'free_shipping' => true,
                'location' => 'Kuala Lumpur',
                'badge' => null,
                'is_featured' => false,
            ],

            // Groceries
            [
                'shop_id' => 5,
                'name' => 'Organic Ground Coffee Beans 500g',
                'category' => 'Groceries',
                'price' => 28,
                'original_price' => 42,
                'discount_percentage' => 33,
                'rating' => 4.7,
                'sold_count' => 5674,
                'stock' => 234,
                'free_shipping' => true,
                'location' => 'Shah Alam',
                'badge' => null,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
