@extends('logistics.layouts.app')
@section('title','Delivery Assignment')
@section('page-title','Delivery Assignment')
@section('content')
<div class="page-header"><div><p class="page-kicker">Dispatch control</p><h2>Assign sorted parcels to riders</h2><p>Match delivery zones with available riders and release ready parcel batches.</p></div><div class="page-actions"><a class="button" href="{{ route('logistics.dispatch.monitoring') }}"><i data-lucide="map-pinned"></i>Monitor deliveries</a></div></div>
<section class="metric-strip"><article class="metric-item"><span class="metric-icon"><i data-lucide="package-check"></i></span><span class="metric-copy"><small>Ready to dispatch</small><strong>29</strong><span>Across 3 zones</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="bike"></i></span><span class="metric-copy"><small>Available riders</small><strong>5</strong><span>2 nearing capacity</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="route"></i></span><span class="metric-copy"><small>Active routes</small><strong>12</strong><span>47 parcels in transit</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="clock-3"></i></span><span class="metric-copy"><small>Next dispatch cutoff</small><strong>3:30 PM</strong><span>42 minutes remaining</span></span></article></section>
<section class="panel"><div class="panel-header"><div><h3>Zone dispatch board</h3><p>Only active riders assigned to the selected area are shown.</p></div><span class="status-badge is-success">Facility ready</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Zone / Area</th><th>Ready parcels</th><th>Rider availability</th><th>Assign rider</th><th>Dispatch state</th><th>Action</th></tr></thead><tbody>
@foreach($zones as $zone)<tr data-dispatch-zone="{{ $zone['zone'] }}"><td><span class="cell-title"><strong>{{ $zone['zone'] }}</strong><small>{{ $zone['area'] }}</small></span></td><td><strong>{{ $zone['ready'] }}</strong> parcels</td><td>{{ count($zone['riders']) }} available</td><td><select class="filter-select" data-rider-select><option value="">Choose active rider</option>@foreach($zone['riders'] as $rider)<option>{{ $rider }}</option>@endforeach</select></td><td><span data-dispatch-status>Awaiting assignment</span></td><td><button class="button button-small button-primary" type="button" data-dispatch-action>Assign & dispatch</button></td></tr>@endforeach
</tbody></table></div></section>
<div class="content-grid equal" style="margin-top:20px"><section class="panel"><div class="panel-header"><div><h3>Rider capacity</h3><p>Estimated load before the next cutoff.</p></div></div><div class="panel-body attention-list">@foreach([['Nico Flores',8,12],['Anne Cruz',6,10],['Marco Lim',5,14]] as [$name,$load,$capacity])<div class="attention-item"><i data-lucide="bike"></i><span><strong>{{ $name }}</strong><small>{{ $load }} of {{ $capacity }} parcel slots assigned</small></span><div class="progress-track"><span style="width:{{ round($load/$capacity*100) }}%"></span></div></div>@endforeach</div></section><section class="panel"><div class="panel-header"><div><h3>Dispatch checklist</h3><p>Complete before releasing a batch.</p></div></div><div class="panel-body">@foreach(['Parcel count matches the dispatch manifest','Rider identity and vehicle verified','Delivery route and exceptions reviewed','Rider has acknowledged the assignment'] as $item)<label class="toggle-row"><span class="toggle-copy"><strong>{{ $item }}</strong></span><span class="switch"><input type="checkbox"><span></span></span></label>@endforeach</div></section></div>
@endsection
