@extends('logistics.layouts.app')
@section('title','Delivery Monitoring')
@section('page-title','Delivery Monitoring')
@section('content')
<div class="page-header"><div><p class="page-kicker">Live operations</p><h2>Track active delivery runs</h2><p>Follow each dispatch from rider assignment through successful delivery or exception handling.</p></div><div class="page-actions"><button class="button" type="button" onclick="location.reload()"><i data-lucide="refresh-cw"></i>Refresh preview</button></div></div>
<section class="metric-strip"><article class="metric-item"><span class="metric-icon"><i data-lucide="user-round-check"></i></span><span class="metric-copy"><small>Assigned</small><strong>5</strong><span>Waiting to depart</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="truck"></i></span><span class="metric-copy"><small>Out for delivery</small><strong>47</strong><span>Across 12 active routes</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="circle-check-big"></i></span><span class="metric-copy"><small>Delivered today</small><strong>132</strong><span>94.3% success rate</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="triangle-alert"></i></span><span class="metric-copy"><small>Exceptions</small><strong>4</strong><span>Needs operator follow-up</span></span></article></section>
<section class="panel" data-table-scope><div class="table-toolbar"><div class="search-field"><i data-lucide="search"></i><input type="search" data-table-search placeholder="Search dispatch, rider, zone, or last update"></div><select class="filter-select" data-filter-status><option value="">All stages</option><option value="ASSIGNED_TO_RIDER">Assigned</option><option value="OUT_FOR_DELIVERY">Out for Delivery</option><option value="DELIVERED">Delivered</option><option value="DELIVERY_FAILED">Exception / Failed</option></select></div><div class="table-wrap"><table class="data-table"><thead><tr><th data-sort>Dispatch</th><th>Rider</th><th>Zone</th><th>Parcels</th><th>Route progress</th><th>Current stage</th><th>Last update</th><th>Action</th></tr></thead><tbody>
@foreach($deliveries as $delivery)<tr data-row data-record-row data-record-type="deliveries" data-record-id="{{ $delivery['id'] }}" data-status="{{ $delivery['status'] }}"><td><strong>{{ $delivery['id'] }}</strong></td><td>{{ $delivery['rider'] }}</td><td>{{ $delivery['zone'] }}</td><td>{{ $delivery['parcels'] }}</td><td><div class="row-actions"><div class="progress-track"><span style="width:{{ $delivery['progress'] }}%"></span></div><small>{{ $delivery['progress'] }}%</small></div></td><td><span class="status-badge" data-status-badge data-status="{{ $delivery['status'] }}">{{ str($delivery['status'])->replace('_',' ')->title() }}</span></td><td>{{ $delivery['last'] }}</td><td><button class="button button-small" type="button" data-modal-open="delivery-{{ $delivery['id'] }}">View timeline</button></td></tr>@endforeach
<tr><td class="empty-row" colspan="8" data-empty-row>No delivery runs match these filters.</td></tr></tbody></table></div></section>
@foreach($deliveries as $delivery)<section class="modal" data-modal="delivery-{{ $delivery['id'] }}" hidden><div class="modal-header"><div><h3>{{ $delivery['id'] }} delivery timeline</h3><p>{{ $delivery['rider'] }} · {{ $delivery['zone'] }}</p></div><button class="icon-button" type="button" data-modal-close><i data-lucide="x"></i></button></div><div class="modal-body"><div class="activity-list"><div class="activity-item"><span class="activity-time">1:05 PM</span><span class="activity-dot"></span><span class="activity-copy"><strong>Assigned to rider</strong><small>Manifest acknowledged at the sorting center</small></span></div><div class="activity-item"><span class="activity-time">1:22 PM</span><span class="activity-dot"></span><span class="activity-copy"><strong>Out for delivery</strong><small>Rider departed with {{ $delivery['parcels'] }} parcels</small></span></div><div class="activity-item"><span class="activity-time">Latest</span><span class="activity-dot"></span><span class="activity-copy"><strong>{{ str($delivery['status'])->replace('_',' ')->title() }}</strong><small>{{ $delivery['last'] }}</small></span></div></div></div><div class="modal-footer">@if($delivery['status']==='DELIVERY_FAILED')<button class="button button-primary" type="button" data-set-status="ASSIGNED_TO_RIDER" data-success="Delivery queued for reassignment.">Reassign delivery</button>@else<button class="button" type="button" data-modal-close>Close</button>@endif</div></section>@endforeach
@endsection
