<?php
namespace Tests\Feature\Admin;
use App\Models\{Cart,CartItem,Category,LogisticsProfile,Parcel,Payment,Product,ProductVariant,SellerProfile,Shipment,ShipmentEvent,Store,User,Waybill};
use Database\Seeders\DatabaseSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Str;use Tests\TestCase;
class Phase5To6AdminTest extends TestCase {use RefreshDatabase;private User $admin;private User $buyer;private Store $store;private ProductVariant $variant;
 protected function setUp():void{parent::setUp();$this->seed(DatabaseSeeder::class);$this->admin=User::where('email','admin@bearly.test')->firstOrFail();$this->buyer=User::factory()->create(['role'=>'buyer','status'=>'active']);$seller=User::factory()->create(['role'=>'seller','status'=>'active']);$category=Category::first();$profile=SellerProfile::create(['user_id'=>$seller->id,'legal_business_name'=>'Commerce Store','approved_category_id'=>$category->id,'approved_at'=>now()]);$this->store=Store::create(['seller_profile_id'=>$profile->id,'name'=>'Commerce Store','slug'=>'commerce-store','publication_status'=>'published']);$product=Product::create(['store_id'=>$this->store->id,'category_id'=>$category->id,'name'=>'Database Product','slug'=>'database-product','product_status'=>'active','compliance_status'=>'clear','published_at'=>now()]);$this->variant=ProductVariant::create(['product_id'=>$product->id,'sku'=>'DB-001','name'=>'Default','price_minor'=>250000,'stock_on_hand'=>10,'low_stock_threshold'=>2]);}
 public function test_checkout_persists_order_groups_items_and_payment():void{$cart=Cart::create(['user_id'=>$this->buyer->id,'status'=>'active']);CartItem::create(['cart_id'=>$cart->id,'product_variant_id'=>$this->variant->id,'quantity'=>2]);$this->actingAs($this->buyer)->post(route('checkout.place'),$this->address())->assertSessionHasNoErrors();$this->assertDatabaseHas('orders',['buyer_id'=>$this->buyer->id,'total_minor'=>500000]);$this->assertDatabaseHas('seller_orders',['store_id'=>$this->store->id,'total_minor'=>500000]);$this->assertDatabaseHas('order_items',['product_variant_id'=>$this->variant->id,'quantity'=>2]);$this->assertDatabaseHas('payments',['amount_minor'=>500000,'status'=>'pending']);$this->assertSame(8,$this->variant->fresh()->stock_on_hand);}
 public function test_paid_order_drives_dashboard_commission_and_is_idempotent():void{$this->placeOrder();$payment=Payment::sole();$payload=['provider_reference'=>'GCASH-REFERENCE-1'];$this->actingAs($this->admin)->post(route('admin.orders.payments.confirm',$payment),$payload)->assertSessionHasNoErrors();$this->actingAs($this->admin)->post(route('admin.orders.payments.confirm',$payment),$payload)->assertSessionHasNoErrors();$this->assertDatabaseCount('platform_commissions',1);$this->assertDatabaseCount('seller_transactions',1);$this->assertDatabaseHas('platform_commissions',['base_amount_minor'=>250000,'amount_minor'=>25000]);$this->assertDatabaseHas('audit_logs',['action'=>'payment.confirmed']);$this->actingAs($this->admin)->get(route('admin.dashboard'))->assertOk()->assertSee('₱2,500.00');$this->actingAs($this->admin)->get(route('admin.commissions'))->assertOk()->assertSee('Commerce Store');}
 public function test_admin_can_query_and_audit_fulfillment_override():void{$sellerOrder=$this->placeOrder();$logisticsUser=User::factory()->create(['role'=>'logistics','status'=>'active']);$logistics=LogisticsProfile::create(['user_id'=>$logisticsUser->id,'legal_name'=>'Logistics','display_name'=>'Logistics','contact_phone'=>'09171234567']);$shipment=Shipment::create(['shipment_no'=>'SHP-TEST-1','seller_order_id'=>$sellerOrder->id,'logistics_profile_id'=>$logistics->id,'status'=>'in_transit']);$waybill=Waybill::create(['shipment_id'=>$shipment->id,'waybill_no'=>'WB-TEST-1','scan_token'=>hash('sha256','test'),'barcode_value'=>'WB-TEST-1','piece_count'=>1,'total_weight_kg'=>1,'generated_at'=>now()]);$parcel=Parcel::create(['shipment_id'=>$shipment->id,'waybill_id'=>$waybill->id,'parcel_no'=>'PCL-TEST-1','piece_sequence'=>1,'weight_kg'=>1,'status'=>'in_transit']);ShipmentEvent::create(['shipment_id'=>$shipment->id,'parcel_id'=>$parcel->id,'event_type'=>'dispatch','to_status'=>'in_transit','source'=>'system','occurred_at'=>now()]);$this->actingAs($this->admin)->get(route('admin.fulfillment'))->assertOk()->assertSee('WB-TEST-1')->assertSee('PCL-TEST-1',false);$this->actingAs($this->admin)->patch(route('admin.fulfillment.override',$shipment),['status'=>'exception','note'=>'Manual investigation required.'])->assertSessionHasNoErrors();$this->assertSame('exception',$shipment->fresh()->status);$this->assertDatabaseHas('shipment_events',['shipment_id'=>$shipment->id,'event_type'=>'admin_override','to_status'=>'exception']);$this->assertDatabaseHas('audit_logs',['action'=>'shipment.status_overridden','auditable_id'=>$shipment->id]);}
 private function placeOrder(){ $cart=Cart::create(['user_id'=>$this->buyer->id,'status'=>'active']);CartItem::create(['cart_id'=>$cart->id,'product_variant_id'=>$this->variant->id,'quantity'=>1]);$this->actingAs($this->buyer)->post(route('checkout.place'),$this->address());return \App\Models\SellerOrder::sole();}
 private function address():array{return ['recipient_name'=>'Buyer Name','recipient_phone'=>'09171234567','address_line'=>'1 Main Street','barangay'=>'San Rafael','city_municipality'=>'San Pablo City','province'=>'Laguna','postal_code'=>'4000','payment_method'=>'gcash'];}
}
