@extends('logistics.layouts.app')
@section('title','Reports')
@section('page-title','Reports')
@section('content')
<div class="page-header"><div><p class="page-kicker">Performance analytics</p><h2>Logistics reports</h2><p>Review parcel throughput, delivery outcomes, sorting performance, and rider productivity.</p></div><div class="page-actions"><button class="button button-primary" type="button" data-report-export><i data-lucide="download"></i>Export CSV</button></div></div>
<section class="panel" style="margin-bottom:20px"><div class="table-toolbar"><div class="field"><label>Report type</label><select class="filter-select"><option>Operations summary</option><option>Rider performance</option><option>Delivery exceptions</option><option>Parcel throughput</option></select></div><div class="field"><label>From</label><input type="date" value="2026-09-14"></div><div class="field"><label>To</label><input type="date" value="2026-09-20"></div><button class="button button-primary" type="button" data-report-apply><i data-lucide="filter"></i>Apply range</button></div></section>
<section class="metric-strip"><article class="metric-item"><span class="metric-icon"><i data-lucide="package"></i></span><span class="metric-copy"><small>Parcel throughput</small><strong>{{ number_format($summary['throughput']) }}</strong><span>Selected reporting period</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="package-check"></i></span><span class="metric-copy"><small>Delivered</small><strong>{{ number_format($summary['delivered']) }}</strong><span>Completed shipments</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="badge-check"></i></span><span class="metric-copy"><small>Success rate</small><strong>{{ $summary['success_rate'] }}%</strong><span>+1.8% versus prior period</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="timer"></i></span><span class="metric-copy"><small>Average sort time</small><strong>{{ $summary['avg_sort_time'] }}</strong><span>Within 20-minute target</span></span></article></section>
<div class="content-grid equal">
    <section class="panel"><div class="panel-header"><div><h3>Daily parcel throughput</h3><p>Packages processed over the selected seven days.</p></div></div><div class="panel-body"><div class="bar-chart">@foreach($dailyVolumes as $index=>$volume)<div class="bar-column"><strong>{{ $volume }}</strong><div class="bar" style="height:{{ round($volume/max($dailyVolumes)*175) }}px"></div><small>{{ ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][$index] }}</small></div>@endforeach</div></div></section>
    <section class="panel"><div class="panel-header"><div><h3>Delivery status breakdown</h3><p>Outcome distribution for the same period.</p></div></div><div class="panel-body breakdown-list">@foreach($statusBreakdown as $item)<div class="breakdown-row"><span>{{ $item['label'] }}</span><div class="breakdown-bar"><span style="width:{{ $item['share'] }}%"></span></div><strong>{{ $item['share'] }}%</strong></div>@endforeach</div></section>
</div>
<section class="panel" style="margin-top:20px"><div class="panel-header"><div><h3>Rider performance</h3><p>Completed assignments and delivery success rates.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Rider</th><th>Assigned</th><th>Delivered</th><th>Failed</th><th>Success rate</th></tr></thead><tbody>@foreach($riderStats as $rider)<tr data-report-row><td><strong>{{ $rider['name'] }}</strong></td><td>{{ $rider['assigned'] }}</td><td>{{ $rider['delivered'] }}</td><td>{{ $rider['failed'] }}</td><td><span class="status-badge is-success">{{ $rider['rate'] }}</span></td></tr>@endforeach</tbody></table></div></section>
@endsection
