<section class="case-deadline-banner"><span><i data-lucide="clock-3"></i></span><div><strong>Seller response required</strong><p>Review the claim and submit one decision before the response window closes.</p></div><div><small>Time remaining</small><strong>{{ $case['deadline'] }}</strong></div></section>
<section class="case-overview-strip"><div><span>Order</span><strong>{{ $case['order'] }}</strong></div><div><span>Customer</span><strong>{{ $case['customer'] }}</strong></div><div><span>Request</span><strong>{{ $case['request'] }}</strong></div><div><span>Claim amount</span><strong>{{ $case['amount'] }}</strong></div></section>
<div class="case-details-layout">
<main class="case-main-column">
    <section class="case-panel"><header class="case-panel-heading"><div><i data-lucide="message-square-text"></i><span><strong>Review buyer claim</strong><small>Check the reason, statement, and submitted proof</small></span></div><span class="case-evidence-count">{{ $case['evidence'] }}</span></header><dl class="case-claim-grid"><div><dt>Product</dt><dd>{{ $case['product'] }}</dd></div><div><dt>SKU</dt><dd>{{ $case['sku'] }}</dd></div><div><dt>Reason</dt><dd>{{ $case['reason'] }}</dd></div><div><dt>Requested resolution</dt><dd>{{ $case['request'] }}</dd></div><div class="is-wide"><dt>Buyer statement</dt><dd>{{ $case['buyer_note'] }}</dd></div></dl><div class="case-evidence-gallery"><button type="button" data-case-preview="Buyer evidence 1"><i data-lucide="image"></i><span>Evidence 1</span></button><button type="button" data-case-preview="Buyer evidence 2"><i data-lucide="image"></i><span>Evidence 2</span></button><button type="button" data-case-preview="All buyer evidence"><i data-lucide="images"></i><span>View all files</span></button></div></section>
    <section class="case-panel"><header class="case-panel-heading"><div><i data-lucide="reply"></i><span><strong>Prepare seller response</strong><small>Your response and evidence enter the case audit trail</small></span></div></header><label class="case-response-field"><span>Response to buyer and reviewer</span><textarea rows="5" maxlength="1000" placeholder="Explain whether you accept or dispute the request and reference your evidence." data-case-response></textarea><small><span data-case-character-count>0</span>/1000 characters</small></label><label class="case-upload"><input type="file" multiple accept="image/*,video/*,.pdf" data-case-evidence-input><i data-lucide="upload-cloud"></i><span><strong>Add seller evidence</strong><small data-case-evidence-name>Images, video, or PDF · Maximum 10 MB per file</small></span></label></section>
</main>
<aside class="case-side-column case-action-sidebar"><section class="case-panel case-summary-panel"><header class="case-panel-heading"><div><i data-lucide="receipt-text"></i><span><strong>Decision impact</strong><small>Review before submitting</small></span></div></header><dl><div><dt>Claim amount</dt><dd>{{ $case['amount'] }}</dd></div><div><dt>Return required</dt><dd>{{ $case['request'] === 'Refund Only' ? 'No' : 'If accepted' }}</dd></div><div><dt>Inventory update</dt><dd>{{ $case['request'] === 'Refund Only' ? 'None' : 'After inspection' }}</dd></div></dl></section><section class="case-panel case-decision-panel"><h3>Choose one decision</h3><p>Accept the request or submit your evidence for platform review.</p><button class="case-accept-button" type="button" data-case-action="accept"><i data-lucide="check"></i>Accept request</button><button class="case-dispute-button" type="button" data-case-action="dispute"><i data-lucide="shield-alert"></i>Dispute request</button><small>You cannot edit the decision after submission.</small></section></aside>
</div>
