<section class="case-deadline-banner is-shipping"><span><i data-lucide="truck"></i></span><div><strong>Return parcel is on the way</strong><p>Monitor the shipment. Inspect and confirm the returned item once delivered.</p></div><div><small>Expected return</small><strong>September 5</strong></div></section>
<section class="case-panel case-tracking-focus">
    <header class="case-panel-heading"><div><i data-lucide="map-pinned"></i><span><strong>Return shipment tracking</strong><small>Live logistics status for {{ $case['tracking'] }}</small></span></div><button class="case-report-button" type="button" data-case-preview="Return delivery issue form"><i data-lucide="triangle-alert"></i>Report delivery issue</button></header>
    <div class="tracking-summary-grid"><div><span>Tracking number</span><strong>{{ $case['tracking'] }}</strong></div><div><span>Courier</span><strong>Bearly Logistics</strong></div><div><span>Latest scan</span><strong>Santa Rosa Sorting Center</strong></div><div><span>Estimated arrival</span><strong>September 5, 2026</strong></div></div>
    <ol class="case-horizontal-timeline"><li class="is-done"><span><i data-lucide="check"></i></span><div><strong>Return approved</strong><small>Aug 30 · 10:15 AM</small></div></li><li class="is-done"><span><i data-lucide="check"></i></span><div><strong>Buyer shipped parcel</strong><small>Sep 1 · 2:42 PM</small></div></li><li class="is-current"><span><i data-lucide="truck"></i></span><div><strong>In transit</strong><small>Sorting center scan</small></div></li><li><span><i data-lucide="package-check"></i></span><div><strong>Seller inspection</strong><small>Pending delivery</small></div></li></ol>
</section>
<div class="case-monitor-layout">
    <section class="case-panel"><header class="case-panel-heading"><div><i data-lucide="package-open"></i><span><strong>Expected return item</strong><small>Use this information during parcel inspection</small></span></div></header><dl class="case-claim-grid"><div><dt>Order</dt><dd>{{ $case['order'] }}</dd></div><div><dt>Customer</dt><dd>{{ $case['customer'] }}</dd></div><div><dt>Product</dt><dd>{{ $case['product'] }}</dd></div><div><dt>SKU</dt><dd>{{ $case['sku'] }}</dd></div><div><dt>Return reason</dt><dd>{{ $case['reason'] }}</dd></div><div><dt>Expected refund</dt><dd>{{ $case['amount'] }}</dd></div></dl></section>
    <aside class="case-side-column"><section class="case-panel case-inspection-panel"><h3>Next seller action</h3><p>The inspection controls become available only after the courier marks the parcel delivered.</p><button type="button" disabled><i data-lucide="clipboard-check"></i>Inspect returned item</button><small>Current requirement: wait for delivery</small></section></aside>
</div>
