@extends('rider.layouts.app')
@section('title','Delivery '.$job['id'])
@section('page-title','Delivery Execution')
@section('content')
<div class="page-header"><div><p class="page-kicker">Delivery process · {{ $job['id'] }}</p><h2>Deliver to {{ $job['customer'] }}</h2><p>Navigate to the customer, verify payment and package details, then capture proof of delivery.</p></div><div class="page-actions"><a class="button" href="{{ route('rider.dashboard.deliveries') }}"><i data-lucide="arrow-left"></i>Back to route</a></div></div>
<div class="workflow-steps"><div class="workflow-step is-complete"><span><i data-lucide="check"></i></span><strong>Package verified</strong></div><div class="workflow-step is-current"><span>2</span><strong>Out for delivery</strong></div><div class="workflow-step"><span>3</span><strong>Customer handoff</strong></div></div>
<div class="route-layout"><section class="section-stack"><article class="panel"><div class="panel-header"><div><h3>Customer route</h3><p>{{ $job['distance'] }} · Estimated {{ $job['estimated_time'] }}</p></div><span class="status-badge is-info">Out for Delivery</span></div><div class="panel-body"><div class="route-map"><span class="map-pin"><i data-lucide="map-pin"></i></span><div class="map-meta"><span><strong>{{ $job['customer'] }}</strong><br>{{ $job['address'] }}</span><span><strong>{{ $job['estimated_time'] }}</strong><br>{{ $job['coordinates'] }}</span></div></div><div class="page-actions" style="margin-top:14px"><button class="button" type="button" data-call-contact="{{ $job['contact'] }}"><i data-lucide="phone"></i>Call customer</button><button class="button button-primary" type="button" data-navigation-preview><i data-lucide="navigation"></i>Open navigation</button></div></div></article><article class="panel"><div class="panel-header"><div><h3>Delivery instructions</h3><p>Buyer note attached to this order.</p></div></div><div class="panel-body"><p style="margin:0;color:var(--muted);font-size:12px;line-height:1.7">{{ $job['notes'] }}</p></div></article></section>
<aside class="section-stack"><section class="panel"><div class="panel-header"><div><h3>Package verification</h3><p>{{ $job['waybill'] }}</p></div></div><div class="panel-body detail-list"><div class="detail-item"><small>Customer</small><strong>{{ $job['customer'] }}</strong></div><div class="detail-item"><small>Contact</small><strong>{{ $job['contact'] }}</strong></div><div class="detail-item"><small>Payment</small><strong>{{ $job['payment'] }}</strong></div><div class="detail-item"><small>Amount to collect</small><strong>{{ $job['amount'] }}</strong></div></div><div class="panel-body" style="padding-top:0"><label class="toggle-row"><span class="toggle-copy"><strong>Package matches waybill</strong><small>Confirm before customer handoff.</small></span><span class="switch"><input type="checkbox" data-delivery-check><span></span></span></label><label class="toggle-row"><span class="toggle-copy"><strong>Payment or prepaid status verified</strong><small>Check after collection or confirmation.</small></span><span class="switch"><input type="checkbox" data-delivery-check><span></span></span></label></div><div class="panel-footer"><button class="button button-primary" style="width:100%" type="button" data-confirm-delivery><i data-lucide="camera"></i>Confirm delivery</button></div></section></aside></div>
<section class="modal" data-modal="proof-delivery" hidden><div class="modal-header"><div><h3>Proof of delivery</h3><p>Capture receiver confirmation before completing {{ $job['id'] }}.</p></div><button class="icon-button" type="button" data-modal-close><i data-lucide="x"></i></button></div><form method="POST" action="{{ route('rider.orders.delivery.confirm',$job['id']) }}" enctype="multipart/form-data" data-job-complete="delivery:{{ $job['id'] }}">@csrf<div class="modal-body"><div class="field-grid"><div class="field"><label>Receiver name <span>*</span></label><input name="receiver_name" required placeholder="Full name"></div><div class="field"><label>Relationship</label><select name="relationship"><option>Customer</option><option>Household member</option><option>Authorized representative</option></select></div><div class="field span-2"><label>Delivery photo <span>*</span></label><label class="proof-preview"><input type="file" name="proof" accept="image/*" required hidden data-proof-file><span><i data-lucide="camera"></i><strong>Choose proof-of-delivery photo</strong><small data-proof-name>JPG or PNG preview file</small></span></label></div><div class="field span-2"><label>Delivery note</label><textarea name="note" placeholder="Optional receiver or location note"></textarea></div></div></div><div class="modal-footer"><button class="button" type="button" data-modal-close>Cancel</button><button class="button button-primary" type="submit">Complete delivery</button></div></form></section>
@endsection
