@extends('layouts.seller')
@section('title', 'Pickup Requests')
@section('page-title', 'Pickup Requests')
@section('content')
<div class="page-heading fulfillment-heading"><div><span class="section-kicker">Logistics coordination</span><h2>Pickup Requests</h2><p>Submit labeled parcels, monitor approval, and confirm rider handover.</p></div><button class="seller-primary-button" type="button" data-modal-open="pickup-create"><i data-lucide="plus"></i>Create Pickup Request</button></div>
@include('seller.fulfillment.partials.summary', ['items' => $summary])
<section class="pickup-ready-banner"><span><i data-lucide="package-check"></i></span><div><strong>2 orders are ready for pickup request</strong><p>Their waybills are printed and parcel details are complete.</p></div><button type="button" data-modal-open="pickup-create">Arrange Pickup<i data-lucide="arrow-right"></i></button></section>
<section class="fulfillment-workspace" data-pickup-workspace>
    <div class="fulfillment-tabs"><button class="is-active" type="button" data-pickup-tab="all">All Requests <span>{{ count($requests) }}</span></button><button type="button" data-pickup-tab="pending">Pending Approval <span>1</span></button><button type="button" data-pickup-tab="assigned">Rider Assigned <span>1</span></button><button type="button" data-pickup-tab="picked-up">Picked Up</button><button type="button" data-pickup-tab="cancelled">Cancelled</button></div>
    <div class="fulfillment-toolbar"><label><i data-lucide="search"></i><input type="search" placeholder="Search request, rider, or pickup address" data-pickup-search></label></div>
    <div class="fulfillment-table-wrap"><table class="fulfillment-table"><thead><tr><th>Request</th><th>Orders / Parcels</th><th>Provider</th><th>Pickup Schedule</th><th>Pickup Address</th><th>Rider</th><th>Status</th><th>Action</th></tr></thead><tbody>
    @foreach($requests as $item)<tr data-pickup-row data-status="{{ $item['status_key'] }}" data-search="{{ strtolower(implode(' ', $item)) }}"><td><strong>{{ $item['id'] }}</strong></td><td><strong>{{ $item['orders'] }}</strong><small>{{ $item['packages'] }} parcels</small></td><td>{{ $item['provider'] }}</td><td>{{ $item['schedule'] }}</td><td>{{ $item['address'] }}</td><td>{{ $item['rider'] }}</td><td><span class="fulfillment-status is-{{ $item['status_key'] }}">{{ $item['status'] }}</span></td><td><button class="fulfillment-row-action" type="button" data-pickup-view data-pickup='@json($item)'>{{ in_array($item['status_key'], ['pending','assigned']) ? 'Manage' : 'View Details' }}</button></td></tr>@endforeach
    </tbody></table><div class="fulfillment-empty" data-pickup-empty hidden><i data-lucide="search-x"></i><strong>No matching pickup requests</strong></div></div><footer class="fulfillment-footer"><span>Showing <strong data-pickup-count>{{ count($requests) }}</strong> requests</span><span>Logistics controls rider assignment and approval.</span></footer>
</section>
<div class="seller-modal fulfillment-modal" data-modal="pickup-create" hidden><button class="modal-backdrop" type="button" data-modal-close></button><section class="modal-card pickup-create-card"><div class="modal-heading"><div><span class="section-kicker">Arrange shipment</span><h3>Create Pickup Request</h3></div><button type="button" data-modal-close><i data-lucide="x"></i></button></div><form class="pickup-form" data-pickup-form><fieldset><legend>Select labeled parcels</legend>@foreach($eligibleOrders as $order)<label class="pickup-order-option"><input type="checkbox" name="orders[]" value="{{ $order['order'] }}" data-pickup-order><span><strong>{{ $order['order'] }}</strong><small>{{ $order['tracking'] }} · {{ $order['packages'] }} parcel · {{ $order['weight'] }}</small></span></label>@endforeach</fieldset><div class="pickup-form-grid"><label><span>Logistics provider</span><select required><option>Bearly Logistics</option></select></label><label><span>Pickup date</span><input type="date" required></label><label><span>Preferred time</span><select required><option value="">Choose time window</option><option>10:00 AM–12:00 PM</option><option>1:00–3:00 PM</option><option>3:00–5:00 PM</option></select></label><label><span>Contact person</span><input type="text" value="Bea Rivera" required></label><label class="is-wide"><span>Pickup address</span><textarea rows="2" required>Juan’s Clothing Shop, Santa Rosa City, Laguna</textarea></label><label class="is-wide"><span>Pickup instructions</span><textarea rows="2" placeholder="Optional instructions for the rider"></textarea></label></div><div class="modal-actions"><button class="draft-button" type="button" data-modal-close>Cancel</button><button class="seller-primary-button" type="submit">Submit Request</button></div></form></section></div>
<div class="seller-modal fulfillment-modal" data-modal="pickup-details" hidden><button class="modal-backdrop" type="button" data-modal-close></button><section class="modal-card"><div class="modal-heading"><div><span class="section-kicker">Pickup request</span><h3 data-pickup-id>Request details</h3></div><button type="button" data-modal-close><i data-lucide="x"></i></button></div><dl class="pickup-detail-list"><div><dt>Status</dt><dd data-pickup-status>—</dd></div><div><dt>Orders and parcels</dt><dd data-pickup-orders>—</dd></div><div><dt>Schedule</dt><dd data-pickup-schedule>—</dd></div><div><dt>Rider</dt><dd data-pickup-rider>—</dd></div><div><dt>Pickup address</dt><dd data-pickup-address>—</dd></div></dl><section class="handover-check"><i data-lucide="scan-line"></i><div><strong>Parcel handover</strong><p>Confirm only after the rider scans and receives every parcel.</p></div></section><div class="modal-actions" data-pickup-actions><button class="draft-button" type="button" data-pickup-cancel>Cancel Request</button><button class="seller-primary-button" type="button" data-pickup-confirm>Confirm Handover</button></div></section></div>
@endsection
