@extends('layouts.seller')
@section('title', 'Waybills')
@section('page-title', 'Waybills')
@section('content')
<div class="page-heading fulfillment-heading"><div><span class="section-kicker">Fulfillment preparation</span><h2>Waybills</h2><p>Generate, print, and audit shipping labels for packed orders.</p></div><button class="seller-primary-button" type="button" data-waybill-bulk disabled><i data-lucide="printer"></i>Print Selected</button></div>
@include('seller.fulfillment.partials.summary', ['items' => $summary])
<section class="fulfillment-workspace" data-waybill-workspace>
    <div class="fulfillment-tabs"><button class="is-active" type="button" data-waybill-tab="all">All <span>{{ count($waybills) }}</span></button><button type="button" data-waybill-tab="ready">Ready to Print <span>3</span></button><button type="button" data-waybill-tab="printed">Printed</button><button type="button" data-waybill-tab="reprint">Reprint Required <span>1</span></button></div>
    <div class="fulfillment-toolbar"><label><i data-lucide="search"></i><input type="search" placeholder="Search order, tracking, or customer" data-waybill-search></label><button type="button" data-waybill-history><i data-lucide="history"></i>Print History</button></div>
    <div class="fulfillment-table-wrap"><table class="fulfillment-table waybill-table"><thead><tr><th><input type="checkbox" data-waybill-check-all aria-label="Select all printable waybills"></th><th>Order / Customer</th><th>Tracking Number</th><th>Courier</th><th>Parcel Details</th><th>Destination</th><th>Pickup</th><th>Status</th><th>Action</th></tr></thead><tbody>
    @foreach($waybills as $item)<tr data-waybill-row data-status="{{ $item['status_key'] }}" data-search="{{ strtolower(implode(' ', $item)) }}"><td><input type="checkbox" data-waybill-check {{ $item['status_key'] === 'printed' ? 'disabled' : '' }} aria-label="Select {{ $item['order'] }}"></td><td><strong>{{ $item['order'] }}</strong><small>{{ $item['customer'] }}</small></td><td><strong>{{ $item['tracking'] }}</strong></td><td>{{ $item['courier'] }}</td><td><strong>{{ $item['packages'] }} {{ $item['packages'] > 1 ? 'packages' : 'package' }}</strong><small>{{ $item['weight'] }} · {{ $item['size'] }}</small></td><td>{{ $item['destination'] }}</td><td>{{ $item['pickup'] }}</td><td><span class="fulfillment-status is-{{ $item['status_key'] }}">{{ $item['status'] }}</span></td><td><button class="fulfillment-row-action" type="button" data-waybill-action data-waybill='@json($item)'>{{ $item['action'] }}</button></td></tr>@endforeach
    </tbody></table><div class="fulfillment-empty" data-waybill-empty hidden><i data-lucide="search-x"></i><strong>No matching waybills</strong><span>Try another tab or search term.</span></div></div>
    <footer class="fulfillment-footer"><span>Showing <strong data-waybill-count>{{ count($waybills) }}</strong> records</span><span>Only packed and verified orders can generate waybills.</span></footer>
</section>
<div class="seller-modal fulfillment-modal" data-modal="waybill-preview" hidden><button class="modal-backdrop" type="button" data-modal-close aria-label="Close"></button><section class="modal-card"><div class="modal-heading"><div><span class="section-kicker">Shipping label</span><h3 data-waybill-modal-order>Waybill preview</h3></div><button type="button" data-modal-close><i data-lucide="x"></i></button></div><div class="waybill-label"><div class="waybill-barcode"><i data-lucide="scan-line"></i><strong data-waybill-modal-tracking>Tracking number</strong></div><dl><div><dt>Ship to</dt><dd data-waybill-modal-customer>—</dd></div><div><dt>Destination</dt><dd data-waybill-modal-destination>—</dd></div><div><dt>Courier</dt><dd data-waybill-modal-courier>—</dd></div><div><dt>Parcel</dt><dd data-waybill-modal-parcel>—</dd></div></dl></div><div class="modal-actions"><button class="draft-button" type="button" data-modal-close>Close</button><button class="seller-primary-button" type="button" data-waybill-print><i data-lucide="printer"></i>Print Waybill</button></div></section></div>
<div class="seller-modal fulfillment-modal" data-modal="waybill-history" hidden><button class="modal-backdrop" type="button" data-modal-close></button><section class="modal-card"><div class="modal-heading"><div><span class="section-kicker">Audit log</span><h3>Print History</h3></div><button type="button" data-modal-close><i data-lucide="x"></i></button></div><div class="fulfillment-history">@foreach($history as $entry)<article><span><i data-lucide="printer-check"></i></span><div><strong>{{ $entry['action'] }} · {{ $entry['order'] }}</strong><small>{{ $entry['tracking'] }} · {{ $entry['actor'] }}</small></div><time>{{ $entry['time'] }}</time></article>@endforeach</div></section></div>
@endsection
