<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('roles', function (Blueprint $t) {
            $t->id();
            $t->string('name', 40)->unique();
            $t->string('display_name', 80);
            $t->string('description')->nullable();
            $t->timestamps();
        });
        Schema::create('role_user', function (Blueprint $t) {
            $t->foreignId('role_id')->constrained()->cascadeOnDelete();
            $t->foreignId('user_id')->constrained()->cascadeOnDelete();
            $t->foreignId('assigned_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('assigned_at')->useCurrent();
            $t->primary(['role_id', 'user_id']);
        });
        Schema::create('addresses', function (Blueprint $t) {
            $t->id();
            $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();
            $t->string('label', 50)->default('Home');
            $t->string('recipient_name', 160);
            $t->string('phone', 30);
            $t->string('house_number', 40)->nullable();
            $t->string('street', 180);
            $t->string('barangay', 120);
            $t->string('city_municipality', 120);
            $t->string('province', 120);
            $t->string('postal_code', 10)->nullable();
            $t->string('psgc_province_code', 20)->nullable();
            $t->string('psgc_city_code', 20)->nullable();
            $t->string('psgc_barangay_code', 20)->nullable();
            $t->decimal('latitude', 10, 7)->nullable();
            $t->decimal('longitude', 10, 7)->nullable();
            $t->boolean('is_default_shipping')->default(false);
            $t->boolean('is_default_pickup')->default(false);
            $t->timestamps();
            $t->softDeletes();
            $t->index(['user_id', 'is_default_shipping']);
        });
        Schema::create('categories', function (Blueprint $t) {
            $t->id();
            $t->foreignId('parent_id')->nullable()->constrained('categories')->nullOnDelete();
            $t->string('name', 120);
            $t->string('slug', 140)->unique();
            $t->text('description')->nullable();
            $t->boolean('is_restricted')->default(false);
            $t->boolean('is_active')->default(true);
            $t->unsignedInteger('position')->default(0);
            $t->timestamps();
            $t->unique(['parent_id', 'name']);
        });
        Schema::create('account_applications', function (Blueprint $t) {
            $t->id();
            $t->string('application_no', 30)->unique();
            $t->foreignId('user_id')->constrained()->restrictOnDelete();
            $t->foreignId('requested_role_id')->constrained('roles')->restrictOnDelete();
            $t->string('business_name', 160)->nullable();
            $t->foreignId('business_category_id')->nullable()->constrained('categories')->nullOnDelete();
            $t->string('status', 32)->default('draft')->index();
            $t->timestamp('submitted_at')->nullable();
            $t->timestamp('review_started_at')->nullable();
            $t->timestamp('decided_at')->nullable();
            $t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();
            $t->text('decision_reason')->nullable();
            $t->text('revision_notes')->nullable();
            $t->timestamps();
            $t->index(['requested_role_id', 'status', 'submitted_at']);
        });
        Schema::create('application_documents', function (Blueprint $t) {
            $t->id();
            $t->foreignId('application_id')->constrained('account_applications')->cascadeOnDelete();
            $t->string('document_type', 50);
            $t->string('file_path', 500);
            $t->string('original_name');
            $t->string('mime_type', 100);
            $t->unsignedBigInteger('size_bytes');
            $t->string('verification_status', 30)->default('pending');
            $t->foreignId('verified_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('verified_at')->nullable();
            $t->text('rejection_reason')->nullable();
            $t->timestamps();
            $t->index(['application_id', 'document_type']);
        });
        Schema::create('seller_profiles', function (Blueprint $t) {
            $t->id();
            $t->foreignId('user_id')->unique()->constrained()->restrictOnDelete();
            $t->foreignId('application_id')->nullable()->constrained('account_applications')->nullOnDelete();
            $t->string('legal_business_name', 160);
            $t->foreignId('approved_category_id')->nullable()->constrained('categories')->restrictOnDelete();
            $t->foreignId('pickup_address_id')->nullable()->constrained('addresses')->nullOnDelete();
            $t->unsignedSmallInteger('commission_rate_bps')->default(1000);
            $t->string('standing_status', 30)->default('good_standing');
            $t->unsignedSmallInteger('warning_points')->default(0);
            $t->timestamp('approved_at')->nullable();
            $t->timestamps();
            $t->softDeletes();
        });
        Schema::create('logistics_profiles', function (Blueprint $t) {
            $t->id();
            $t->foreignId('user_id')->unique()->constrained()->restrictOnDelete();
            $t->foreignId('application_id')->nullable()->constrained('account_applications')->nullOnDelete();
            $t->string('legal_name', 160);
            $t->string('display_name', 160);
            $t->string('contact_phone', 30);
            $t->string('status', 30)->default('active');
            $t->timestamps();
            $t->softDeletes();
        });
        Schema::table('account_applications', function (Blueprint $t) {
            $t->foreignId('sponsor_logistics_profile_id')->nullable()->after('requested_role_id')->constrained('logistics_profiles')->nullOnDelete();
        });
        Schema::create('stores', function (Blueprint $t) {
            $t->id();
            $t->foreignId('seller_profile_id')->unique()->constrained()->restrictOnDelete();
            $t->string('name', 160);
            $t->string('slug', 180)->unique();
            $t->text('description')->nullable();
            $t->string('contact_email')->nullable();
            $t->string('contact_phone', 30)->nullable();
            $t->string('logo_path', 500)->nullable();
            $t->string('banner_path', 500)->nullable();
            $t->string('publication_status', 30)->default('draft');
            $t->timestamp('published_at')->nullable();
            $t->timestamps();
            $t->softDeletes();
        });
        Schema::create('sorting_centers', function (Blueprint $t) {
            $t->id();
            $t->foreignId('logistics_profile_id')->constrained()->restrictOnDelete();
            $t->foreignId('address_id')->constrained('addresses')->restrictOnDelete();
            $t->string('name', 160);
            $t->string('code', 30)->unique();
            $t->string('contact_phone', 30)->nullable();
            $t->string('operating_hours', 100)->nullable();
            $t->unsignedInteger('daily_capacity')->nullable();
            $t->string('status', 20)->default('active');
            $t->timestamps();
            $t->softDeletes();
        });
        Schema::create('sorting_zones', function (Blueprint $t) {
            $t->id();
            $t->foreignId('sorting_center_id')->constrained()->cascadeOnDelete();
            $t->string('code', 30);
            $t->string('name', 120);
            $t->json('destination_rules')->nullable();
            $t->string('status', 20)->default('active');
            $t->timestamps();
            $t->unique(['sorting_center_id', 'code']);
        });
        Schema::create('rider_profiles', function (Blueprint $t) {
            $t->id();
            $t->foreignId('user_id')->unique()->constrained()->restrictOnDelete();
            $t->foreignId('logistics_profile_id')->constrained()->restrictOnDelete();
            $t->foreignId('home_sorting_center_id')->nullable()->constrained('sorting_centers')->nullOnDelete();
            $t->foreignId('current_zone_id')->nullable()->constrained('sorting_zones')->nullOnDelete();
            $t->string('vehicle_type', 80);
            $t->string('vehicle_model', 100)->nullable();
            $t->string('plate_number', 30)->nullable();
            $t->unsignedSmallInteger('parcel_capacity')->nullable();
            $t->string('emergency_contact_name', 160)->nullable();
            $t->string('emergency_contact_phone', 30)->nullable();
            $t->string('availability_status', 30)->default('offline');
            $t->string('verification_status', 30)->default('pending');
            $t->timestamps();
            $t->softDeletes();
            $t->index(['logistics_profile_id', 'availability_status']);
        });

        Schema::create('products', function (Blueprint $t) {
            $t->id();
            $t->foreignId('store_id')->constrained()->restrictOnDelete();
            $t->foreignId('category_id')->constrained()->restrictOnDelete();
            $t->string('name', 180);
            $t->string('slug', 220);
            $t->text('description')->nullable();
            $t->string('product_status', 30)->default('draft');
            $t->string('compliance_status', 30)->default('pending_scan');
            $t->boolean('voucher_eligible')->default(false);
            $t->timestamp('published_at')->nullable();
            $t->timestamp('archived_at')->nullable();
            $t->timestamp('removed_at')->nullable();
            $t->text('removed_reason')->nullable();
            $t->timestamps();
            $t->softDeletes();
            $t->unique(['store_id', 'slug']);
            $t->index(['store_id', 'product_status']);
            $t->index(['compliance_status', 'updated_at']);
        });
        Schema::create('product_variants', function (Blueprint $t) {
            $t->id();
            $t->foreignId('product_id')->constrained()->cascadeOnDelete();
            $t->string('sku', 80)->unique();
            $t->string('name', 140);
            $t->json('options')->nullable();
            $t->unsignedBigInteger('price_minor');
            $t->unsignedBigInteger('compare_at_price_minor')->nullable();
            $t->unsignedInteger('stock_on_hand')->default(0);
            $t->unsignedInteger('stock_reserved')->default(0);
            $t->unsignedInteger('low_stock_threshold')->default(5);
            $t->decimal('weight_kg', 10, 3)->nullable();
            $t->boolean('is_active')->default(true);
            $t->unsignedSmallInteger('position')->default(0);
            $t->timestamps();
            $t->softDeletes();
            $t->index(['product_id', 'is_active']);
        });
        Schema::create('product_images', function (Blueprint $t) {
            $t->id();
            $t->foreignId('product_id')->constrained()->cascadeOnDelete();
            $t->foreignId('variant_id')->nullable()->constrained('product_variants')->cascadeOnDelete();
            $t->string('path', 500);
            $t->string('alt_text')->nullable();
            $t->unsignedSmallInteger('position')->default(0);
            $t->boolean('is_primary')->default(false);
            $t->timestamps();
            $t->index(['product_id', 'position']);
        });
        Schema::create('inventory_movements', function (Blueprint $t) {
            $t->id();
            $t->foreignId('variant_id')->constrained('product_variants')->restrictOnDelete();
            $t->string('type', 40);
            $t->integer('quantity_delta');
            $t->unsignedInteger('balance_after');
            $t->string('reference_type', 50)->nullable();
            $t->unsignedBigInteger('reference_id')->nullable();
            $t->string('reason')->nullable();
            $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('occurred_at');
            $t->timestamp('created_at')->useCurrent();
            $t->index(['variant_id', 'occurred_at']);
            $t->index(['reference_type', 'reference_id']);
        });
        Schema::create('carts', function (Blueprint $t) {
            $t->id();
            $t->foreignId('user_id')->nullable()->constrained()->cascadeOnDelete();
            $t->string('session_token', 100)->nullable();
            $t->string('status', 20)->default('active');
            $t->timestamp('expires_at')->nullable();
            $t->timestamps();
            $t->index(['session_token', 'status']);
        });
        Schema::create('cart_items', function (Blueprint $t) {
            $t->id();
            $t->foreignId('cart_id')->constrained()->cascadeOnDelete();
            $t->foreignId('product_variant_id')->constrained()->cascadeOnDelete();
            $t->unsignedInteger('quantity')->default(1);
            $t->boolean('selected')->default(true);
            $t->timestamps();
            $t->unique(['cart_id', 'product_variant_id']);
        });
        Schema::create('wishlists', function (Blueprint $t) {
            $t->id();
            $t->foreignId('user_id')->nullable()->constrained()->cascadeOnDelete();
            $t->string('session_token', 100)->nullable();
            $t->foreignId('product_id')->constrained()->cascadeOnDelete();
            $t->timestamp('created_at')->useCurrent();
            $t->unique(['user_id', 'product_id']);
            $t->index(['session_token', 'product_id']);
        });

        Schema::create('orders', function (Blueprint $t) {
            $t->id();
            $t->string('order_no', 32)->unique();
            $t->foreignId('buyer_id')->constrained('users')->restrictOnDelete();
            $t->foreignId('shipping_address_id')->nullable()->constrained('addresses')->nullOnDelete();
            $t->string('recipient_name', 160);
            $t->string('recipient_phone', 30);
            $t->string('address_line', 255);
            $t->string('barangay', 120);
            $t->string('city_municipality', 120);
            $t->string('province', 120);
            $t->string('postal_code', 10)->nullable();
            $t->char('currency', 3)->default('PHP');
            $t->unsignedBigInteger('subtotal_minor');
            $t->unsignedBigInteger('shipping_fee_minor')->default(0);
            $t->unsignedBigInteger('discount_minor')->default(0);
            $t->unsignedBigInteger('total_minor');
            $t->string('status', 30)->default('pending_payment');
            $t->string('payment_status', 30)->default('unpaid');
            $t->timestamp('placed_at')->nullable();
            $t->timestamp('cancelled_at')->nullable();
            $t->timestamp('completed_at')->nullable();
            $t->text('cancel_reason')->nullable();
            $t->timestamps();
            $t->index(['buyer_id', 'created_at']);
            $t->index(['status', 'created_at']);
        });
        Schema::create('seller_orders', function (Blueprint $t) {
            $t->id();
            $t->string('seller_order_no', 32)->unique();
            $t->foreignId('order_id')->constrained()->restrictOnDelete();
            $t->foreignId('store_id')->constrained()->restrictOnDelete();
            $t->string('status', 30)->default('placed');
            $t->unsignedBigInteger('subtotal_minor');
            $t->unsignedBigInteger('discount_minor')->default(0);
            $t->unsignedBigInteger('shipping_fee_minor')->default(0);
            $t->unsignedBigInteger('total_minor');
            $t->timestamp('fulfillment_deadline_at')->nullable();
            $t->timestamp('confirmed_at')->nullable();
            $t->timestamp('preparing_at')->nullable();
            $t->timestamp('ready_at')->nullable();
            $t->timestamp('handed_over_at')->nullable();
            $t->timestamp('delivered_at')->nullable();
            $t->timestamp('completed_at')->nullable();
            $t->timestamp('cancelled_at')->nullable();
            $t->text('seller_note')->nullable();
            $t->timestamps();
            $t->unique(['order_id', 'store_id']);
            $t->index(['store_id', 'status', 'created_at']);
        });
        Schema::create('order_items', function (Blueprint $t) {
            $t->id();
            $t->foreignId('seller_order_id')->constrained()->restrictOnDelete();
            $t->foreignId('product_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('product_variant_id')->nullable()->constrained()->nullOnDelete();
            $t->string('product_name', 180);
            $t->string('variant_name', 140);
            $t->string('sku', 80);
            $t->json('options')->nullable();
            $t->unsignedBigInteger('unit_price_minor');
            $t->unsignedInteger('quantity');
            $t->unsignedBigInteger('discount_minor')->default(0);
            $t->unsignedBigInteger('subtotal_minor');
            $t->timestamps();
        });
        Schema::create('payments', function (Blueprint $t) {
            $t->id();
            $t->string('payment_no', 40)->unique();
            $t->foreignId('order_id')->constrained()->restrictOnDelete();
            $t->string('method', 30);
            $t->string('provider', 50)->nullable();
            $t->string('provider_reference', 150)->nullable()->index();
            $t->unsignedBigInteger('amount_minor');
            $t->string('status', 30)->default('pending');
            $t->timestamp('initiated_at')->nullable();
            $t->timestamp('authorized_at')->nullable();
            $t->timestamp('paid_at')->nullable();
            $t->timestamp('failed_at')->nullable();
            $t->timestamp('refunded_at')->nullable();
            $t->text('failure_reason')->nullable();
            $t->json('metadata')->nullable();
            $t->timestamps();
            $t->index(['order_id', 'status']);
        });

        Schema::create('shipments', function (Blueprint $t) {
            $t->id();
            $t->string('shipment_no', 32)->unique();
            $t->foreignId('seller_order_id')->constrained()->restrictOnDelete();
            $t->foreignId('logistics_profile_id')->constrained()->restrictOnDelete();
            $t->foreignId('origin_address_id')->nullable()->constrained('addresses')->nullOnDelete();
            $t->foreignId('destination_address_id')->nullable()->constrained('addresses')->nullOnDelete();
            $t->string('purpose', 20)->default('outbound');
            $t->string('status', 40)->default('pending_waybill');
            $t->unsignedBigInteger('shipping_fee_minor')->default(0);
            $t->unsignedBigInteger('cod_amount_minor')->default(0);
            $t->timestamp('cod_collected_at')->nullable();
            $t->timestamp('estimated_delivery_at')->nullable();
            $t->timestamp('delivered_at')->nullable();
            $t->timestamp('returned_at')->nullable();
            $t->timestamps();
            $t->index(['seller_order_id', 'status']);
            $t->index(['logistics_profile_id', 'status']);
        });
        Schema::create('waybills', function (Blueprint $t) {
            $t->id();
            $t->foreignId('shipment_id')->unique()->constrained()->restrictOnDelete();
            $t->string('waybill_no', 40)->unique();
            $t->char('scan_token', 64)->unique();
            $t->string('barcode_value', 120)->unique();
            $t->unsignedSmallInteger('piece_count')->default(1);
            $t->decimal('total_weight_kg', 10, 3);
            $t->decimal('length_cm', 10, 2)->nullable();
            $t->decimal('width_cm', 10, 2)->nullable();
            $t->decimal('height_cm', 10, 2)->nullable();
            $t->string('status', 30)->default('generated');
            $t->foreignId('generated_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('generated_at');
            $t->timestamp('printed_at')->nullable();
            $t->unsignedSmallInteger('print_count')->default(0);
            $t->timestamp('voided_at')->nullable();
            $t->text('void_reason')->nullable();
            $t->timestamps();
        });
        Schema::create('parcels', function (Blueprint $t) {
            $t->id();
            $t->foreignId('shipment_id')->constrained()->restrictOnDelete();
            $t->foreignId('waybill_id')->constrained()->restrictOnDelete();
            $t->string('parcel_no', 50)->unique();
            $t->unsignedSmallInteger('piece_sequence');
            $t->decimal('weight_kg', 10, 3);
            $t->decimal('length_cm', 10, 2)->nullable();
            $t->decimal('width_cm', 10, 2)->nullable();
            $t->decimal('height_cm', 10, 2)->nullable();
            $t->string('size_class', 20)->nullable();
            $t->string('status', 40)->default('created');
            $t->foreignId('current_sorting_center_id')->nullable()->constrained('sorting_centers')->nullOnDelete();
            $t->foreignId('current_zone_id')->nullable()->constrained('sorting_zones')->nullOnDelete();
            $t->timestamp('last_event_at')->nullable();
            $t->timestamps();
            $t->unique(['waybill_id', 'piece_sequence']);
            $t->index(['status', 'current_sorting_center_id']);
        });
        Schema::create('pickup_requests', function (Blueprint $t) {
            $t->id();
            $t->string('pickup_no', 32)->unique();
            $t->foreignId('store_id')->constrained()->restrictOnDelete();
            $t->foreignId('logistics_profile_id')->constrained()->restrictOnDelete();
            $t->foreignId('pickup_address_id')->constrained('addresses')->restrictOnDelete();
            $t->string('status', 30)->default('requested');
            $t->date('requested_date');
            $t->dateTime('window_start');
            $t->dateTime('window_end');
            $t->text('seller_instructions')->nullable();
            $t->foreignId('verified_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('verified_at')->nullable();
            $t->timestamp('cancelled_at')->nullable();
            $t->timestamp('completed_at')->nullable();
            $t->text('cancellation_reason')->nullable();
            $t->timestamps();
            $t->index(['logistics_profile_id', 'status', 'requested_date']);
        });
        Schema::create('pickup_request_parcels', function (Blueprint $t) {
            $t->foreignId('pickup_request_id')->constrained()->cascadeOnDelete();
            $t->foreignId('parcel_id')->constrained()->restrictOnDelete();
            $t->timestamp('added_at')->useCurrent();
            $t->primary(['pickup_request_id', 'parcel_id']);
        });
        Schema::create('pickup_assignments', function (Blueprint $t) {
            $t->id();
            $t->foreignId('pickup_request_id')->constrained()->restrictOnDelete();
            $t->foreignId('rider_profile_id')->constrained()->restrictOnDelete();
            $t->string('status', 30)->default('assigned');
            $t->foreignId('assigned_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('assigned_at');
            $t->timestamp('accepted_at')->nullable();
            $t->timestamp('arrived_at')->nullable();
            $t->timestamp('picked_up_at')->nullable();
            $t->timestamp('completed_at')->nullable();
            $t->timestamp('cancelled_at')->nullable();
            $t->text('notes')->nullable();
            $t->timestamps();
            $t->index(['rider_profile_id', 'status', 'assigned_at']);
        });
        Schema::create('dispatch_batches', function (Blueprint $t) {
            $t->id();
            $t->string('batch_no', 32)->unique();
            $t->foreignId('sorting_center_id')->constrained()->restrictOnDelete();
            $t->foreignId('sorting_zone_id')->nullable()->constrained()->restrictOnDelete();
            $t->foreignId('rider_profile_id')->constrained()->restrictOnDelete();
            $t->string('status', 30)->default('preparing');
            $t->foreignId('prepared_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('prepared_at')->nullable();
            $t->timestamp('assigned_at')->nullable();
            $t->timestamp('dispatched_at')->nullable();
            $t->timestamp('completed_at')->nullable();
            $t->timestamp('cancelled_at')->nullable();
            $t->timestamps();
        });
        Schema::create('dispatch_batch_parcels', function (Blueprint $t) {
            $t->foreignId('dispatch_batch_id')->constrained()->cascadeOnDelete();
            $t->foreignId('parcel_id')->constrained()->restrictOnDelete();
            $t->unsignedSmallInteger('sequence')->nullable();
            $t->timestamp('loaded_at')->nullable();
            $t->primary(['dispatch_batch_id', 'parcel_id']);
        });
        Schema::create('shipment_events', function (Blueprint $t) {
            $t->id();
            $t->foreignId('shipment_id')->constrained()->restrictOnDelete();
            $t->foreignId('parcel_id')->nullable()->constrained()->restrictOnDelete();
            $t->string('event_type', 50);
            $t->string('from_status', 40)->nullable();
            $t->string('to_status', 40);
            $t->foreignId('sorting_center_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('sorting_zone_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('actor_user_id')->nullable()->constrained('users')->nullOnDelete();
            $t->string('source', 20)->default('system');
            $t->string('scan_method', 20)->nullable();
            $t->text('notes')->nullable();
            $t->json('metadata')->nullable();
            $t->timestamp('occurred_at');
            $t->timestamp('created_at')->useCurrent();
            $t->index(['shipment_id', 'occurred_at']);
            $t->index(['parcel_id', 'occurred_at']);
        });
        Schema::create('delivery_attempts', function (Blueprint $t) {
            $t->id();
            $t->foreignId('parcel_id')->constrained()->restrictOnDelete();
            $t->foreignId('dispatch_batch_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('rider_profile_id')->constrained()->restrictOnDelete();
            $t->unsignedSmallInteger('attempt_no');
            $t->string('outcome', 30);
            $t->string('failure_reason', 100)->nullable();
            $t->text('notes')->nullable();
            $t->decimal('latitude', 10, 7)->nullable();
            $t->decimal('longitude', 10, 7)->nullable();
            $t->timestamp('attempted_at');
            $t->timestamp('next_attempt_at')->nullable();
            $t->timestamps();
            $t->unique(['parcel_id', 'attempt_no']);
        });
        Schema::create('delivery_proofs', function (Blueprint $t) {
            $t->id();
            $t->foreignId('delivery_attempt_id')->constrained()->cascadeOnDelete();
            $t->string('type', 30);
            $t->string('file_path', 500)->nullable();
            $t->string('recipient_name', 160)->nullable();
            $t->string('recipient_signature_path', 500)->nullable();
            $t->timestamp('otp_verified_at')->nullable();
            $t->timestamp('captured_at');
            $t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamps();
        });

        Schema::create('compliance_rules', function (Blueprint $t) {
            $t->id();
            $t->string('code', 50)->unique();
            $t->string('name', 160);
            $t->string('rule_type', 40);
            $t->string('target_field', 40);
            $t->text('pattern')->nullable();
            $t->foreignId('category_id')->nullable()->constrained()->nullOnDelete();
            $t->string('severity', 20);
            $t->string('default_action', 30);
            $t->json('configuration')->nullable();
            $t->boolean('is_active')->default(true);
            $t->unsignedInteger('version')->default(1);
            $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamps();
        });
        Schema::create('product_compliance_checks', function (Blueprint $t) {
            $t->id();
            $t->foreignId('product_id')->constrained()->restrictOnDelete();
            $t->string('trigger', 20);
            $t->string('status', 30)->default('queued');
            $t->string('result', 30)->nullable();
            $t->string('name_snapshot', 180);
            $t->text('description_snapshot')->nullable();
            $t->foreignId('category_id_snapshot')->nullable()->constrained('categories')->nullOnDelete();
            $t->string('rules_version', 50)->nullable();
            $t->timestamp('started_at')->nullable();
            $t->timestamp('completed_at')->nullable();
            $t->text('error_message')->nullable();
            $t->timestamps();
            $t->index(['product_id', 'created_at']);
        });
        Schema::create('product_compliance_check_matches', function (Blueprint $t) {
            $t->id();
            $t->foreignId('check_id')->constrained('product_compliance_checks')->cascadeOnDelete();
            $t->foreignId('rule_id')->constrained('compliance_rules')->restrictOnDelete();
            $t->string('matched_field', 40);
            $t->string('matched_excerpt', 500)->nullable();
            $t->decimal('score', 5, 4)->nullable();
            $t->string('severity', 20);
            $t->string('recommended_action', 30);
            $t->timestamps();
        });
        Schema::create('product_reports', function (Blueprint $t) {
            $t->id();
            $t->string('report_no', 32)->unique();
            $t->foreignId('product_id')->constrained()->restrictOnDelete();
            $t->foreignId('reporter_user_id')->nullable()->constrained('users')->nullOnDelete();
            $t->string('reason_code', 50);
            $t->text('details')->nullable();
            $t->string('status', 30)->default('submitted');
            $t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('reviewed_at')->nullable();
            $t->timestamps();
        });
        Schema::create('product_violations', function (Blueprint $t) {
            $t->id();
            $t->string('violation_no', 32)->unique();
            $t->foreignId('product_id')->constrained()->restrictOnDelete();
            $t->foreignId('seller_profile_id')->constrained()->restrictOnDelete();
            $t->foreignId('check_id')->nullable()->constrained('product_compliance_checks')->nullOnDelete();
            $t->foreignId('rule_id')->nullable()->constrained('compliance_rules')->nullOnDelete();
            $t->foreignId('product_report_id')->nullable()->constrained()->nullOnDelete();
            $t->string('source', 30);
            $t->string('violation_type', 50);
            $t->string('severity', 20);
            $t->text('reason');
            $t->string('detected_excerpt', 500)->nullable();
            $t->string('status', 30)->default('flagged');
            $t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('reviewed_at')->nullable();
            $t->timestamp('resolved_at')->nullable();
            $t->string('resolution', 40)->nullable();
            $t->text('admin_note')->nullable();
            $t->timestamps();
            $t->index(['status', 'severity', 'created_at']);
        });
        Schema::create('violation_actions', function (Blueprint $t) {
            $t->id();
            $t->foreignId('violation_id')->constrained('product_violations')->cascadeOnDelete();
            $t->string('action_type', 40);
            $t->string('from_status', 30)->nullable();
            $t->string('to_status', 30)->nullable();
            $t->foreignId('actor_user_id')->nullable()->constrained('users')->nullOnDelete();
            $t->text('reason')->nullable();
            $t->json('metadata')->nullable();
            $t->timestamp('created_at')->useCurrent();
        });
        Schema::create('seller_warnings', function (Blueprint $t) {
            $t->id();
            $t->string('warning_no', 32)->unique();
            $t->foreignId('seller_profile_id')->constrained()->restrictOnDelete();
            $t->foreignId('violation_id')->nullable()->constrained('product_violations')->nullOnDelete();
            $t->string('level', 20);
            $t->unsignedSmallInteger('points')->default(0);
            $t->text('reason');
            $t->string('status', 20)->default('active');
            $t->foreignId('issued_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('issued_at');
            $t->timestamp('expires_at')->nullable();
            $t->timestamp('acknowledged_at')->nullable();
            $t->timestamp('revoked_at')->nullable();
            $t->timestamps();
        });

        Schema::create('return_requests', function (Blueprint $t) {
            $t->id();
            $t->string('return_no', 32)->unique();
            $t->foreignId('order_id')->constrained()->restrictOnDelete();
            $t->foreignId('seller_order_id')->constrained()->restrictOnDelete();
            $t->foreignId('buyer_id')->constrained('users')->restrictOnDelete();
            $t->foreignId('store_id')->constrained()->restrictOnDelete();
            $t->string('request_type', 30);
            $t->string('reason_code', 50);
            $t->text('buyer_note')->nullable();
            $t->text('seller_response')->nullable();
            $t->string('status', 40)->default('submitted');
            $t->unsignedBigInteger('requested_amount_minor');
            $t->timestamp('response_due_at')->nullable();
            $t->timestamp('submitted_at');
            $t->timestamp('seller_responded_at')->nullable();
            $t->timestamp('reviewed_at')->nullable();
            $t->timestamp('resolved_at')->nullable();
            $t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();
            $t->text('resolution')->nullable();
            $t->foreignId('return_shipment_id')->nullable()->constrained('shipments')->nullOnDelete();
            $t->timestamps();
        });
        Schema::create('return_items', function (Blueprint $t) {
            $t->id();
            $t->foreignId('return_request_id')->constrained()->cascadeOnDelete();
            $t->foreignId('order_item_id')->constrained()->restrictOnDelete();
            $t->unsignedInteger('quantity');
            $t->string('condition_code', 40)->nullable();
            $t->string('resolution', 30)->nullable();
            $t->unsignedBigInteger('refund_amount_minor')->default(0);
            $t->timestamps();
            $t->unique(['return_request_id', 'order_item_id']);
        });
        Schema::create('return_evidence', function (Blueprint $t) {
            $t->id();
            $t->foreignId('return_request_id')->constrained()->cascadeOnDelete();
            $t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();
            $t->string('type', 30);
            $t->string('file_path', 500);
            $t->string('original_name');
            $t->string('description', 500)->nullable();
            $t->timestamp('created_at')->useCurrent();
        });
        Schema::create('refunds', function (Blueprint $t) {
            $t->id();
            $t->string('refund_no', 40)->unique();
            $t->foreignId('return_request_id')->nullable()->constrained()->restrictOnDelete();
            $t->foreignId('payment_id')->nullable()->constrained()->restrictOnDelete();
            $t->foreignId('order_id')->constrained()->restrictOnDelete();
            $t->unsignedBigInteger('amount_minor');
            $t->string('status', 30)->default('pending');
            $t->string('method', 30);
            $t->string('provider_reference', 150)->nullable();
            $t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('approved_at')->nullable();
            $t->timestamp('processed_at')->nullable();
            $t->timestamp('completed_at')->nullable();
            $t->timestamp('failed_at')->nullable();
            $t->text('failure_reason')->nullable();
            $t->timestamps();
        });
        Schema::create('disputes', function (Blueprint $t) {
            $t->id();
            $t->string('dispute_no', 32)->unique();
            $t->foreignId('seller_order_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('return_request_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('shipment_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('opened_by')->constrained('users')->restrictOnDelete();
            $t->string('subject', 180);
            $t->text('description');
            $t->string('priority', 20)->default('normal');
            $t->string('status', 30)->default('open');
            $t->unsignedBigInteger('amount_minor')->nullable();
            $t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('opened_at');
            $t->timestamp('response_due_at')->nullable();
            $t->timestamp('resolved_at')->nullable();
            $t->timestamp('closed_at')->nullable();
            $t->text('resolution')->nullable();
            $t->timestamps();
        });
        Schema::create('dispute_participants', function (Blueprint $t) {
            $t->foreignId('dispute_id')->constrained()->cascadeOnDelete();
            $t->foreignId('user_id')->constrained()->restrictOnDelete();
            $t->string('participant_role', 30);
            $t->timestamp('joined_at')->useCurrent();
            $t->primary(['dispute_id', 'user_id']);
        });
        Schema::create('dispute_evidence', function (Blueprint $t) {
            $t->id();
            $t->foreignId('dispute_id')->constrained()->cascadeOnDelete();
            $t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();
            $t->string('type', 30);
            $t->string('file_path', 500);
            $t->string('original_name');
            $t->string('description', 500)->nullable();
            $t->timestamp('created_at')->useCurrent();
        });
        Schema::create('dispute_events', function (Blueprint $t) {
            $t->id();
            $t->foreignId('dispute_id')->constrained()->cascadeOnDelete();
            $t->string('event_type', 40);
            $t->foreignId('actor_user_id')->nullable()->constrained('users')->nullOnDelete();
            $t->string('from_status', 30)->nullable();
            $t->string('to_status', 30)->nullable();
            $t->text('note')->nullable();
            $t->json('metadata')->nullable();
            $t->timestamp('created_at')->useCurrent();
        });

        Schema::create('platform_commissions', function (Blueprint $t) {
            $t->id();
            $t->foreignId('seller_order_id')->constrained()->restrictOnDelete();
            $t->foreignId('refund_id')->nullable()->constrained()->restrictOnDelete();
            $t->string('type', 30);
            $t->unsignedBigInteger('base_amount_minor');
            $t->unsignedSmallInteger('rate_bps');
            $t->bigInteger('amount_minor');
            $t->string('status', 30)->default('estimated');
            $t->timestamp('calculated_at');
            $t->timestamp('finalized_at')->nullable();
            $t->timestamp('reversed_at')->nullable();
            $t->timestamps();
        });
        Schema::create('seller_transactions', function (Blueprint $t) {
            $t->id();
            $t->string('transaction_no', 40)->unique();
            $t->foreignId('seller_profile_id')->constrained()->restrictOnDelete();
            $t->foreignId('seller_order_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('payment_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('refund_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('commission_id')->nullable()->constrained('platform_commissions')->nullOnDelete();
            $t->string('type', 40);
            $t->bigInteger('amount_minor');
            $t->string('status', 30)->default('pending');
            $t->timestamp('available_at')->nullable();
            $t->timestamp('posted_at')->nullable();
            $t->string('description')->nullable();
            $t->timestamps();
            $t->index(['seller_profile_id', 'status', 'created_at']);
        });
        Schema::create('seller_payouts', function (Blueprint $t) {
            $t->id();
            $t->string('payout_no', 40)->unique();
            $t->foreignId('seller_profile_id')->constrained()->restrictOnDelete();
            $t->date('period_start');
            $t->date('period_end');
            $t->unsignedBigInteger('gross_minor');
            $t->unsignedBigInteger('commission_minor');
            $t->bigInteger('adjustment_minor')->default(0);
            $t->unsignedBigInteger('net_minor');
            $t->string('status', 30)->default('pending');
            $t->timestamp('due_at')->nullable();
            $t->timestamp('paid_at')->nullable();
            $t->string('reference', 150)->nullable();
            $t->timestamps();
        });
        Schema::create('rider_earnings', function (Blueprint $t) {
            $t->id();
            $t->foreignId('rider_profile_id')->constrained()->restrictOnDelete();
            $t->foreignId('pickup_assignment_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('delivery_attempt_id')->nullable()->constrained()->nullOnDelete();
            $t->string('type', 30);
            $t->bigInteger('amount_minor');
            $t->string('status', 30)->default('pending');
            $t->string('description')->nullable();
            $t->timestamp('earned_at');
            $t->timestamp('posted_at')->nullable();
            $t->timestamp('paid_at')->nullable();
            $t->timestamps();
        });

        Schema::create('conversations', function (Blueprint $t) {
            $t->id();
            $t->string('subject', 180)->nullable();
            $t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('seller_order_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('product_id')->nullable()->constrained()->nullOnDelete();
            $t->foreignId('dispute_id')->nullable()->constrained()->nullOnDelete();
            $t->string('type', 30)->default('direct');
            $t->string('status', 20)->default('open');
            $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('last_message_at')->nullable()->index();
            $t->timestamps();
        });
        Schema::create('conversation_participants', function (Blueprint $t) {
            $t->foreignId('conversation_id')->constrained()->cascadeOnDelete();
            $t->foreignId('user_id')->constrained()->restrictOnDelete();
            $t->string('participant_role', 30);
            $t->timestamp('last_read_at')->nullable();
            $t->timestamp('joined_at')->useCurrent();
            $t->primary(['conversation_id', 'user_id']);
        });
        Schema::create('messages', function (Blueprint $t) {
            $t->id();
            $t->foreignId('conversation_id')->constrained()->cascadeOnDelete();
            $t->foreignId('sender_id')->nullable()->constrained('users')->nullOnDelete();
            $t->text('body');
            $t->string('message_type', 20)->default('text');
            $t->timestamp('sent_at');
            $t->timestamp('edited_at')->nullable();
            $t->timestamp('deleted_at')->nullable();
            $t->timestamps();
            $t->index(['conversation_id', 'sent_at']);
        });
        Schema::create('message_attachments', function (Blueprint $t) {
            $t->id();
            $t->foreignId('message_id')->constrained()->cascadeOnDelete();
            $t->string('file_path', 500);
            $t->string('original_name');
            $t->string('mime_type', 100);
            $t->unsignedBigInteger('size_bytes');
            $t->timestamps();
        });
        Schema::create('notifications', function (Blueprint $t) {
            $t->uuid('id')->primary();
            $t->string('type');
            $t->morphs('notifiable');
            $t->text('data');
            $t->timestamp('read_at')->nullable();
            $t->timestamps();
        });
        Schema::create('user_notification_preferences', function (Blueprint $t) {
            $t->id();
            $t->foreignId('user_id')->constrained()->cascadeOnDelete();
            $t->string('event_key', 80);
            $t->boolean('in_app')->default(true);
            $t->boolean('email')->default(false);
            $t->timestamps();
            $t->unique(['user_id', 'event_key']);
        });
        Schema::create('announcements', function (Blueprint $t) {
            $t->id();
            $t->string('announcement_no', 32)->unique();
            $t->string('title', 180);
            $t->text('body');
            $t->string('status', 20)->default('draft');
            $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('publish_at')->nullable();
            $t->timestamp('published_at')->nullable();
            $t->timestamp('expires_at')->nullable();
            $t->timestamps();
        });
        Schema::create('announcement_roles', function (Blueprint $t) {
            $t->foreignId('announcement_id')->constrained()->cascadeOnDelete();
            $t->foreignId('role_id')->constrained()->cascadeOnDelete();
            $t->primary(['announcement_id', 'role_id']);
        });
        Schema::create('policies', function (Blueprint $t) {
            $t->id();
            $t->string('code', 50)->unique();
            $t->string('title', 180);
            $t->string('category', 80);
            $t->string('status', 20)->default('active');
            $t->timestamps();
        });
        Schema::create('policy_versions', function (Blueprint $t) {
            $t->id();
            $t->foreignId('policy_id')->constrained()->cascadeOnDelete();
            $t->string('version', 20);
            $t->longText('body');
            $t->text('summary')->nullable();
            $t->string('status', 20)->default('draft');
            $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamp('effective_at')->nullable();
            $t->timestamp('published_at')->nullable();
            $t->timestamps();
            $t->unique(['policy_id', 'version']);
        });
        Schema::create('audit_logs', function (Blueprint $t) {
            $t->id();
            $t->foreignId('actor_user_id')->nullable()->constrained('users')->nullOnDelete();
            $t->string('action', 100);
            $t->string('module', 80);
            $t->string('auditable_type', 100)->nullable();
            $t->unsignedBigInteger('auditable_id')->nullable();
            $t->text('description')->nullable();
            $t->json('old_values')->nullable();
            $t->json('new_values')->nullable();
            $t->string('ip_address', 45)->nullable();
            $t->text('user_agent')->nullable();
            $t->string('severity', 20)->default('info');
            $t->timestamp('created_at')->useCurrent();
            $t->index(['auditable_type', 'auditable_id']);
        });
        Schema::create('system_settings', function (Blueprint $t) {
            $t->id();
            $t->string('key', 100)->unique();
            $t->json('value');
            $t->string('value_type', 20);
            $t->boolean('is_public')->default(false);
            $t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamps();
        });
        Schema::create('support_tickets', function (Blueprint $t) {
            $t->id();
            $t->string('ticket_no', 32)->unique();
            $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();
            $t->string('name', 160)->nullable();
            $t->string('email')->nullable();
            $t->string('role_label', 50)->nullable();
            $t->string('topic', 80);
            $t->string('subject', 180);
            $t->text('message');
            $t->string('reference', 50)->nullable();
            $t->string('status', 30)->default('open');
            $t->string('priority', 20)->default('normal');
            $t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();
            $t->timestamps();
        });
    }

    public function down(): void
    {
        if (Schema::hasTable('account_applications')) {
            Schema::table('account_applications', fn (Blueprint $t) => $t->dropConstrainedForeignId('sponsor_logistics_profile_id'));
        }
        foreach ([
            'support_tickets', 'system_settings', 'audit_logs', 'policy_versions', 'policies', 'announcement_roles', 'announcements', 'user_notification_preferences', 'notifications', 'message_attachments', 'messages', 'conversation_participants', 'conversations', 'rider_earnings', 'seller_payouts', 'seller_transactions', 'platform_commissions', 'dispute_events', 'dispute_evidence', 'dispute_participants', 'disputes', 'refunds', 'return_evidence', 'return_items', 'return_requests', 'seller_warnings', 'violation_actions', 'product_violations', 'product_reports', 'product_compliance_check_matches', 'product_compliance_checks', 'compliance_rules', 'delivery_proofs', 'delivery_attempts', 'shipment_events', 'dispatch_batch_parcels', 'dispatch_batches', 'pickup_assignments', 'pickup_request_parcels', 'pickup_requests', 'parcels', 'waybills', 'shipments', 'payments', 'order_items', 'seller_orders', 'orders', 'wishlists', 'cart_items', 'carts', 'inventory_movements', 'product_images', 'product_variants', 'products', 'rider_profiles', 'sorting_zones', 'sorting_centers', 'stores', 'logistics_profiles', 'seller_profiles', 'application_documents', 'account_applications', 'categories', 'addresses', 'role_user', 'roles',
        ] as $table) {
            Schema::dropIfExists($table);
        }
    }
};
