@extends('layouts.admin')
@section('title','Order Management')
@section('page-title','Order Management')
@section('content')
<section class="page-hero"><div><span class="eyebrow">Commerce monitoring</span><h1>Orders and payments</h1><p>Inspect persisted Buyer orders, seller allocations, item breakdowns, and payment state.</p></div><div class="hero-context-stat"><span class="hero-context-icon"><i data-lucide="shopping-bag"></i></span><div><strong>{{ $orders->total() }}</strong><span>Recorded orders</span></div></div></section>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">Order ledger</span><h2>Marketplace orders</h2></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Buyer</th><th>Seller groups</th><th>Total</th><th>Payment</th><th>Status</th><th class="align-right">Details</th></tr></thead><tbody>
@forelse($orders as $order)<tr><td><strong>{{ $order->order_no }}</strong><small class="table-subline">{{ $order->placed_at?->format('M j, Y g:i A') }}</small></td><td>{{ $order->buyer->name }}</td><td>{{ $order->sellerOrders->count() }}</td><td>₱{{ number_format($order->total_minor/100,2) }}</td><td><span class="status-badge {{ $order->payment_status==='paid'?'badge-success':'badge-warning' }}">{{ str($order->payment_status)->title() }}</span></td><td>{{ str($order->status)->replace('_',' ')->title() }}</td><td class="align-right"><button class="button button-ghost button-small" type="button" data-open-modal="order-{{ $order->id }}"><i data-lucide="eye"></i> View</button></td></tr>
@empty<tr><td colspan="7"><div class="table-empty"><i data-lucide="shopping-bag"></i><strong>No orders yet</strong><span>Buyer checkout records will appear here.</span></div></td></tr>@endforelse
</tbody></table></div></section>{{ $orders->links() }}
@foreach($orders as $order)<div class="modal-shell" data-modal="order-{{ $order->id }}" hidden><button type="button" class="modal-backdrop" data-close-modal></button><section class="modal-card modal-wide" role="dialog" aria-modal="true"><div class="modal-heading"><div><span class="eyebrow">{{ $order->order_no }}</span><h2>Order details</h2></div><button type="button" class="icon-button" data-close-modal><i data-lucide="x"></i></button></div><div class="review-details"><div class="detail-grid"><div><span>Recipient</span><strong>{{ $order->recipient_name }}</strong></div><div><span>Address</span><strong>{{ $order->address_line }}, {{ $order->barangay }}, {{ $order->city_municipality }}</strong></div><div><span>Payment status</span><strong>{{ str($order->payment_status)->title() }}</strong></div><div><span>Grand total</span><strong>₱{{ number_format($order->total_minor/100,2) }}</strong></div></div>@foreach($order->sellerOrders as $sellerOrder)<div class="detail-note"><span>{{ $sellerOrder->store->name }} · {{ $sellerOrder->seller_order_no }}</span><p>@foreach($sellerOrder->items as $item){{ $item->quantity }}× {{ $item->product_name }} ({{ $item->variant_name }}) — ₱{{ number_format($item->subtotal_minor/100,2) }}@if(!$loop->last)<br>@endif @endforeach</p></div>@endforeach
@php($payment=$order->payments->sortByDesc('id')->first()) @if($payment && $payment->status!=='paid')<form method="POST" action="{{ route('admin.orders.payments.confirm',$payment) }}">@csrf<label class="form-field"><span>Provider/reference number</span><input name="provider_reference" required maxlength="150"></label><div class="modal-footer"><button class="button button-primary" type="submit"><i data-lucide="circle-check"></i> Confirm payment</button></div></form>@endif</div></section></div>@endforeach
@endsection
