@extends('logistics.layouts.app')
@section('title','Incoming Parcels')
@section('page-title','Incoming Parcels')
@section('content')
<div class="page-header"><div><p class="page-kicker">Sorting center intake</p><h2>Receive and log incoming parcels</h2><p>Record every package arriving from pickup riders before it enters the sorting queue.</p></div><div class="page-actions"><button class="button button-primary" type="button" data-modal-open="log-parcel"><i data-lucide="scan-line"></i>Log incoming parcel</button></div></div>
<section class="metric-strip"><article class="metric-item"><span class="metric-icon"><i data-lucide="package-open"></i></span><span class="metric-copy"><small>Received today</small><strong>146</strong><span>From 22 seller pickups</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="list-checks"></i></span><span class="metric-copy"><small>Awaiting sorting</small><strong>38</strong><span>6 priority parcels</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="scale"></i></span><span class="metric-copy"><small>Total weight</small><strong>284 kg</strong><span>Today’s intake</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="triangle-alert"></i></span><span class="metric-copy"><small>Intake exceptions</small><strong>1</strong><span>Requires inspection</span></span></article></section>
<section class="panel" data-table-scope>
    <div class="table-toolbar"><div class="search-field"><i data-lucide="search"></i><input type="search" data-table-search placeholder="Scan or search waybill, order, seller, or rider"></div><select class="filter-select" data-filter-status><option value="">All intake statuses</option><option value="AT_SORTING_CENTER">At Sorting Center</option><option>Logged</option><option>Ready for Sorting</option><option>Exception</option></select><select class="filter-select" data-filter-zone><option value="">All destinations</option><option>San Pablo North</option><option>San Pablo South</option><option>Calauan / Bay</option><option>Pila / Sta. Cruz</option></select></div>
    <div class="table-wrap"><table class="data-table"><thead><tr><th data-sort>Waybill / Order</th><th>Seller</th><th>Received from</th><th data-sort>Received at</th><th>Pieces</th><th>Weight</th><th>Destination</th><th>Status</th><th>Action</th></tr></thead><tbody data-incoming-body>
    @foreach($incomingParcels as $parcel)
        <tr data-row data-record-row data-record-type="incoming" data-record-id="{{ $parcel['waybill'] }}" data-status="{{ $parcel['status'] }}" data-zone="{{ $parcel['destination'] }}"><td><span class="cell-title"><strong>{{ $parcel['waybill'] }}</strong><small>{{ $parcel['order'] }}</small></span></td><td>{{ $parcel['seller'] }}</td><td>{{ $parcel['rider'] }}</td><td>{{ $parcel['received'] }}</td><td>{{ $parcel['pieces'] }}</td><td>{{ $parcel['weight'] }}</td><td>{{ $parcel['destination'] }}</td><td><span class="status-badge" data-status-badge data-status="{{ $parcel['status'] }}">{{ str($parcel['status'])->replace('_',' ')->title() }}</span></td><td><button class="button button-small" type="button" data-send-sorting>Send to sorting</button></td></tr>
    @endforeach
    <tr><td class="empty-row" colspan="9" data-empty-row>No incoming parcels match these filters.</td></tr></tbody></table></div>
</section>
<section class="modal" data-modal="log-parcel" hidden><div class="modal-header"><div><h3>Log incoming parcel</h3><p>Enter or scan the package details at the intake desk.</p></div><button class="icon-button" type="button" data-modal-close><i data-lucide="x"></i></button></div><form class="modal-body" data-incoming-form><div class="field-grid"><div class="field"><label>Waybill number <span>*</span></label><input name="waybill" required placeholder="BRL-000000"></div><div class="field"><label>Order number <span>*</span></label><input name="order" required placeholder="ORD-00000"></div><div class="field"><label>Seller <span>*</span></label><input name="seller" required></div><div class="field"><label>Pickup rider <span>*</span></label><input name="rider" required></div><div class="field"><label>Pieces <span>*</span></label><input type="number" min="1" name="pieces" required></div><div class="field"><label>Total weight (kg) <span>*</span></label><input type="number" min=".1" step=".1" name="weight" required></div><div class="field span-2"><label>Destination area <span>*</span></label><select name="destination" required><option value="">Select destination</option><option>San Pablo North</option><option>San Pablo South</option><option>Calauan / Bay</option><option>Pila / Sta. Cruz</option></select></div></div><div class="form-actions"><button class="button" type="button" data-modal-close>Cancel</button><button class="button button-primary" type="submit">Log parcel</button></div></form></section>
@endsection
