@extends('rider.layouts.app')
@section('title','Earnings')
@section('page-title','Earnings')
@section('content')
<div class="page-header"><div><p class="page-kicker">Rider finance</p><h2>Profit and earnings dashboard</h2><p>Track completed jobs, incentive bonuses, deductions, pending payouts, and net rider income.</p></div><div class="page-actions"><button class="button button-primary" type="button" data-export-earnings><i data-lucide="download"></i>Export statement</button></div></div>
<section class="metric-strip"><article class="metric-item"><span class="metric-icon"><i data-lucide="sun"></i></span><span class="metric-copy"><small>Today</small><strong>₱{{ number_format($earnings['today']) }}</strong><span>6 completed jobs</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="calendar-days"></i></span><span class="metric-copy"><small>This week</small><strong>₱{{ number_format($earnings['week']) }}</strong><span>23% above last week</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="calendar-range"></i></span><span class="metric-copy"><small>This month</small><strong>₱{{ number_format($earnings['month']) }}</strong><span>{{ $earnings['completed_jobs'] }} completed jobs</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="clock-3"></i></span><span class="metric-copy"><small>Pending payout</small><strong>₱{{ number_format($earnings['pending']) }}</strong><span>Next release on Friday</span></span></article></section>
<div class="content-grid equal" style="margin-bottom:20px"><section class="panel"><div class="panel-header"><div><h3>Earnings breakdown</h3><p>Current month additions and platform deductions.</p></div></div><div class="panel-body"><div class="finance-breakdown"><div class="finance-item"><small>Customer tips</small><strong>+₱{{ number_format($earnings['tips']) }}</strong></div><div class="finance-item"><small>Performance incentives</small><strong>+₱{{ number_format($earnings['incentives']) }}</strong></div><div class="finance-item is-deduction"><small>Platform deductions</small><strong>−₱{{ number_format($earnings['deductions']) }}</strong></div></div></div></section><section class="panel"><div class="panel-header"><div><h3>Payout status</h3><p>Current settlement cycle.</p></div><span class="status-badge is-warning">Processing</span></div><div class="panel-body attention-list"><div class="attention-item"><i data-lucide="landmark"></i><span><strong>GCash ending in 8821</strong><small>Primary payout method</small></span></div><div class="attention-item"><i data-lucide="calendar-check"></i><span><strong>September 25, 2026</strong><small>Expected payout date</small></span></div></div></section></div>
<section class="panel" data-table-scope><div class="panel-header"><div><h3>Earnings activity</h3><p>Filter job income across your selected reporting period.</p></div></div><div class="table-toolbar"><div class="search-field"><i data-lucide="search"></i><input type="search" data-table-search placeholder="Search job ID or type"></div><input class="filter-select" type="date" value="2026-09-01" data-earnings-from><input class="filter-select" type="date" value="2026-09-20" data-earnings-to><select class="filter-select" data-filter-status><option value="">All payout states</option><option>Posted</option><option>Pending</option></select><button class="button button-small" type="button" data-apply-earnings><i data-lucide="filter"></i>Apply</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th data-sort>Date</th><th data-sort>Job</th><th>Type</th><th>Gross amount</th><th>Status</th></tr></thead><tbody>@foreach($logs as $log)<tr data-row data-status="{{ $log['status'] }}" data-earnings-row><td>{{ $log['date'] }}</td><td><strong>{{ $log['job'] }}</strong></td><td>{{ $log['type'] }}</td><td>₱{{ number_format($log['amount']) }}</td><td><span class="status-badge" data-status="{{ $log['status'] }}">{{ $log['status'] }}</span></td></tr>@endforeach<tr><td class="empty-row" colspan="5" data-empty-row>No earnings entries match these filters.</td></tr></tbody></table></div></section>
@endsection
