@extends('layouts.rider')
@section('title','Delivery Process') @section('page-title','Delivery Execution')
@section('content')
<div class="page-intro"><div><span class="eyebrow">Delivery Process</span><h2>Delivery {{ $job['id'] }}</h2><p>Navigate to the buyer, verify package and payment details, then confirm successful handoff.</p></div></div>
@if(session('job_status'))<div class="flash">{{ session('job_status') }}</div>@endif
<div class="stepper"><div class="step is-active">1. Package verified</div><div class="step is-active">2. En route</div><div class="step">3. Customer handoff</div></div>
<div class="route-card"><section class="card"><div class="card-head"><h3>Drop-off details</h3></div><div class="card-body"><span class="eyebrow">Customer</span><h3>{{ $job['customer'] }}</h3><p style="font-size:10.5px;line-height:1.7">{{ $job['address'] }}</p><div class="actions"><button class="btn btn-secondary" data-mock-action="Calling {{ $job['contact'] }}."><i data-lucide="phone"></i>Call customer</button><button class="btn btn-secondary" data-mock-action="Route navigation preview opened."><i data-lucide="navigation"></i>Open route</button></div><div class="file-box" style="margin-top:15px"><strong>Delivery note</strong><br>{{ $job['notes'] }}</div></div></section>
<aside class="card"><div class="card-head"><h3>Package verification</h3></div><div class="card-body"><p class="table-title">{{ $job['waybill'] }}</p><p style="font-size:10px;color:var(--muted)">Payment: <strong>{{ $job['payment'] }}</strong><br>Amount to collect: <strong>{{ $job['amount'] }}</strong></p><label class="checkrow"><input type="checkbox"><span><strong>Package matches waybill</strong><small>Confirm before handoff.</small></span></label><label class="checkrow"><input type="checkbox"><span><strong>Payment / handoff verified</strong><small>Check after customer receives parcel.</small></span></label><form method="POST" action="{{ route('rider.deliver.confirm',$job['id']) }}" style="margin-top:14px">@csrf<button class="btn btn-primary" style="width:100%"><i data-lucide="circle-check"></i>Confirm Delivery</button></form></div></aside></div>
@endsection
