<?php
namespace App\Http\Controllers;
use App\Models\{Order,Payment,PlatformCommission,SellerTransaction};
use App\Services\{AuditService,CommissionLedgerService};
use Illuminate\Http\{RedirectResponse,Request};
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;
class AdminCommerceController extends Controller {
 public function orders(Request $request):View{$orders=Order::with(['buyer','sellerOrders.store','sellerOrders.items','payments'])->latest()->paginate(15);return view('admin.finance.orders',$this->base($request)+compact('orders'));}
 public function confirmPayment(Request $request,Payment $payment,CommissionLedgerService $ledger,AuditService $audit):RedirectResponse{$data=$request->validate(['provider_reference'=>['required','string','max:150']]);DB::transaction(function()use($request,$payment,$data,$ledger,$audit){$payment=Payment::lockForUpdate()->findOrFail($payment->id);$old=$payment->status;$payment->update(['status'=>'paid','provider_reference'=>$data['provider_reference'],'authorized_at'=>$payment->authorized_at??now(),'paid_at'=>now()]);$payment->order()->update(['payment_status'=>'paid']);$ledger->finalize($payment);$audit->record('payment.confirmed','finance',$payment,'Administrator confirmed an order payment.',['status'=>$old],['status'=>'paid','reference'=>$data['provider_reference']],'warning',$request);},3);return back()->with('success','Payment confirmed and commission ledger finalized.');}
 public function commissions(Request $request):View{$rows=PlatformCommission::with('sellerOrder.order','sellerOrder.store')->latest('calculated_at')->get();$ledger=$rows->map(fn($row)=>['date'=>$row->calculated_at?->format('M j, Y')??$row->created_at->format('M j, Y'),'order'=>$row->sellerOrder->order->order_no,'seller'=>$row->sellerOrder->store->name,'gross'=>$row->base_amount_minor/100,'commission'=>$row->amount_minor/100,'sellerNet'=>($row->base_amount_minor-$row->amount_minor)/100])->all();$rate=(float)(\App\Models\SystemSetting::where('key','commission_rate')->first()?->value??10);return view('admin.finance.commissions',$this->base($request)+compact('ledger','rate'));}
 public function transactions(Request $request):View{$rows=SellerTransaction::with(['sellerOrder.order.buyer','sellerOrder.store','payment'])->latest()->get();$transactions=$rows->map(fn($row)=>['id'=>$row->transaction_no,'date'=>$row->created_at->format('Y-m-d'),'order'=>$row->sellerOrder?->order?->order_no??'—','seller'=>$row->sellerOrder?->store?->name??'—','buyer'=>$row->sellerOrder?->order?->buyer?->name??'—','method'=>str($row->payment?->method??'system')->title(),'gross'=>($row->sellerOrder?->total_minor??0)/100,'refund'=>0,'status'=>str($row->status)->title(),'commission'=>($row->sellerOrder?->total_minor-$row->amount_minor)/100,'sellerNet'=>$row->amount_minor/100])->all();$rate=(float)(\App\Models\SystemSetting::where('key','commission_rate')->first()?->value??10);return view('admin.finance.transactions',$this->base($request)+compact('transactions','rate'));}
 private function base(Request $request):array{$admin=$request->user();return ['admin'=>['name'=>$admin->name,'role'=>'Admin','email'=>$admin->email,'initials'=>collect(explode(' ',$admin->name))->map(fn($x)=>strtoupper(substr($x,0,1)))->take(2)->implode('')],'topNotifications'=>[]];}
}
