@extends('logistics.layouts.app')
@section('title','Account')
@section('page-title','Account')
@section('content')
<div class="page-header"><div><p class="page-kicker">Settings</p><h2>Account and facility settings</h2><p>Maintain your operator profile, password, and sorting center information.</p></div></div>
<div data-tab-scope>
    <div class="tabs" data-tabs><button class="tab-button is-active" type="button" data-tab="profile">Profile</button><button class="tab-button" type="button" data-tab="security">Password & security</button><button class="tab-button" type="button" data-tab="facility">Facility</button></div>
    <section class="panel" data-tab-panel="profile" style="margin-top:16px"><div class="panel-header"><div><h3>Operator profile</h3><p>Information displayed throughout Logistics operations.</p></div></div><form class="panel-body" data-preview-form="operatorProfile" data-success="Operator profile saved in this preview."><div class="field-grid"><div class="field"><label>Full name</label><input name="name" value="{{ $operator['name'] }}" required></div><div class="field"><label>Role</label><input name="role" value="{{ $operator['role'] }}" required></div><div class="field"><label>Email address</label><input type="email" name="email" value="{{ $operator['email'] }}" required></div><div class="field"><label>Contact number</label><input name="contact" value="{{ $facility['contact'] }}" required></div></div><div class="form-actions"><button class="button button-primary" type="submit">Save profile</button></div></form></section>
    <section class="panel" data-tab-panel="security" hidden style="margin-top:16px"><div class="panel-header"><div><h3>Change password</h3><p>Use at least eight characters for the preview validation.</p></div></div><form class="panel-body" data-password-form><div class="field-grid"><div class="field span-2"><label>Current password</label><input type="password" name="current_password" required></div><div class="field"><label>New password</label><input type="password" name="new_password" minlength="8" required></div><div class="field"><label>Confirm new password</label><input type="password" name="new_password_confirmation" minlength="8" required></div></div><div class="form-actions"><button class="button button-primary" type="submit">Update password</button></div></form><div class="panel-footer"><label class="toggle-row"><span class="toggle-copy"><strong>Login alerts</strong><small>Show an alert for new browser sign-ins.</small></span><span class="switch"><input type="checkbox" checked><span></span></span></label></div></section>
    <section class="panel" data-tab-panel="facility" hidden style="margin-top:16px"><div class="panel-header"><div><h3>Sorting facility</h3><p>Information used in pickup, intake, and dispatch previews.</p></div></div><form class="panel-body" data-preview-form="facilitySettings" data-success="Facility settings saved in this preview."><div class="field-grid"><div class="field"><label>Business / facility name</label><input name="business_name" value="{{ $facility['business_name'] }}" required></div><div class="field"><label>Contact number</label><input name="contact" value="{{ $facility['contact'] }}" required></div><div class="field span-2"><label>Facility address</label><input name="address" value="{{ $facility['address'] }}" required></div><div class="field"><label>Operating hours</label><input name="operating_hours" value="{{ $facility['operating_hours'] }}" required></div><div class="field"><label>Daily parcel capacity</label><input type="number" min="1" name="daily_capacity" value="{{ $facility['daily_capacity'] }}" required></div></div><div class="form-actions"><button class="button button-primary" type="submit">Save facility settings</button></div></form></section>
</div>
@endsection
