@extends('layouts.logistics')
@section('title','Messages')
@section('page-title','Messages')
@section('content')
<div class="page-header"><div><p class="page-kicker">Coordination hub</p><h2>Operations messaging</h2><p>Coordinate pickups, delivery runs, and approval concerns with Admins, Sellers, and Riders.</p></div><div class="page-actions"><button class="button button-primary" type="button" data-modal-open="new-message"><i data-lucide="square-pen"></i>New conversation</button></div></div>
<section class="chat-shell">
    <aside class="chat-sidebar"><div class="chat-sidebar-head"><div class="search-field"><i data-lucide="search"></i><input type="search" placeholder="Search conversations"></div></div>
    @foreach($conversations as $index=>$conversation)<button class="conversation {{ $index===0 ? 'is-active' : '' }}" type="button" data-conversation="{{ $conversation['id'] }}" data-name="{{ $conversation['name'] }}" data-role="{{ $conversation['role'] }}"><span class="avatar">{{ $conversation['initials'] }}</span><span class="conversation-copy"><strong>{{ $conversation['name'] }}</strong><small>{{ $conversation['preview'] }}</small></span><span class="conversation-time">{{ $conversation['time'] }}</span></button>@endforeach
    </aside>
    <div class="chat-main"><header class="chat-head"><span class="chat-person"><strong data-chat-name></strong><small data-chat-role></small></span><div class="row-actions"><button class="icon-button" type="button" title="View contact details"><i data-lucide="info"></i></button></div></header><div class="chat-messages" data-chat-messages></div><div class="chat-compose"><button class="icon-button" type="button" title="Attach file"><i data-lucide="paperclip"></i></button><input type="text" data-chat-input placeholder="Write a message…"><button class="button button-primary" type="button" data-chat-send><i data-lucide="send"></i>Send</button></div></div>
</section>
<section class="modal" data-modal="new-message" hidden><div class="modal-header"><div><h3>Start a conversation</h3><p>Select an operations contact and prepare your message.</p></div><button class="icon-button" type="button" data-modal-close><i data-lucide="x"></i></button></div><form class="modal-body" data-preview-form="newConversation" data-success="Conversation draft prepared."><div class="field"><label>Contact type</label><select name="type" required><option value="">Select type</option><option>Administrator</option><option>Seller</option><option>Rider</option></select></div><div class="field" style="margin-top:14px"><label>Recipient</label><input name="recipient" required placeholder="Search by name"></div><div class="field" style="margin-top:14px"><label>Message</label><textarea name="message" required placeholder="Describe the operational concern"></textarea></div><div class="form-actions"><button class="button" type="button" data-modal-close>Cancel</button><button class="button button-primary" type="submit">Create draft</button></div></form></section>
@endsection
