@extends('layouts.logistics')
@section('title','Pickup Requests')
@section('page-title','Pickup Requests')
@section('content')
<div class="page-header"><div><p class="page-kicker">Seller coordination</p><h2>Parcel pickup requests</h2><p>Verify seller requests, confirm parcel counts, and schedule approved pickup windows.</p></div><div class="page-actions"><button class="button" type="button" data-modal-open="schedule-pickup"><i data-lucide="calendar-plus"></i>Create pickup</button></div></div>
<section class="metric-strip"><article class="metric-item"><span class="metric-icon"><i data-lucide="clock-3"></i></span><span class="metric-copy"><small>Awaiting review</small><strong>2</strong><span>Requires verification</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="calendar-check"></i></span><span class="metric-copy"><small>Scheduled today</small><strong>7</strong><span>28 total parcels</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="truck"></i></span><span class="metric-copy"><small>In pickup</small><strong>3</strong><span>Riders en route</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="package-check"></i></span><span class="metric-copy"><small>Collected today</small><strong>41</strong><span>Across 9 sellers</span></span></article></section>
<section class="panel" data-table-scope>
    <div class="table-toolbar"><div class="search-field"><i data-lucide="search"></i><input type="search" data-table-search placeholder="Search request, seller, or location"></div><select class="filter-select" data-filter-status><option value="">All statuses</option><option>Pending</option><option>Verified</option><option>Scheduled</option><option>Rejected</option></select></div>
    <div class="table-wrap"><table class="data-table"><thead><tr><th data-sort>Request</th><th data-sort>Seller</th><th>Pickup location</th><th>Parcels</th><th>Requested window</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    @foreach($pickups as $pickup)
        <tr data-row data-record-row data-record-type="pickups" data-record-id="{{ $pickup['id'] }}" data-status="{{ $pickup['status'] }}"><td><strong>{{ $pickup['id'] }}</strong></td><td><span class="cell-title"><strong>{{ $pickup['seller'] }}</strong><small>Verified marketplace seller</small></span></td><td>{{ $pickup['location'] }}</td><td>{{ $pickup['parcels'] }}</td><td>{{ $pickup['window'] }}</td><td><span class="status-badge" data-status-badge data-status="{{ $pickup['status'] }}">{{ $pickup['status'] }}</span></td><td><div class="row-actions"><button class="button button-small" type="button" data-modal-open="pickup-{{ $pickup['id'] }}">Details</button>@if($pickup['status'] === 'Pending')<button class="button button-small button-primary" type="button" data-set-status="Verified" data-success="{{ $pickup['id'] }} verified for scheduling.">Verify</button>@endif</div></td></tr>
    @endforeach
    <tr><td class="empty-row" colspan="7" data-empty-row>No pickup requests match these filters.</td></tr></tbody></table></div>
</section>
@foreach($pickups as $pickup)
<section class="modal" data-modal="pickup-{{ $pickup['id'] }}" hidden><div class="modal-header"><div><h3>{{ $pickup['id'] }} · {{ $pickup['seller'] }}</h3><p>Seller pickup request details.</p></div><button class="icon-button" type="button" data-modal-close><i data-lucide="x"></i></button></div><div class="modal-body"><div class="detail-list"><div class="detail-item"><small>Pickup address</small><strong>{{ $pickup['location'] }}</strong></div><div class="detail-item"><small>Parcel quantity</small><strong>{{ $pickup['parcels'] }} parcels</strong></div><div class="detail-item"><small>Requested window</small><strong>{{ $pickup['window'] }}</strong></div><div class="detail-item"><small>Contact person</small><strong>Seller operations desk</strong></div></div><div class="field" style="margin-top:15px"><label>Internal note</label><textarea placeholder="Add handling or access instructions"></textarea></div></div><div class="modal-footer"><button class="button button-danger" type="button" data-set-status="Rejected" data-success="{{ $pickup['id'] }} rejected.">Reject</button><button class="button button-primary" type="button" data-set-status="Scheduled" data-success="{{ $pickup['id'] }} scheduled for pickup.">Approve & schedule</button></div></section>
@endforeach
<section class="modal" data-modal="schedule-pickup" hidden><div class="modal-header"><div><h3>Create pickup request</h3><p>Add an assisted request for a seller.</p></div><button class="icon-button" type="button" data-modal-close><i data-lucide="x"></i></button></div><form class="modal-body" data-preview-form="manualPickup" data-success="Pickup request added to the preview queue."><div class="field-grid"><div class="field"><label>Seller</label><input required name="seller"></div><div class="field"><label>Parcel count</label><input required type="number" min="1" name="parcels"></div><div class="field span-2"><label>Pickup address</label><input required name="address"></div><div class="field"><label>Date</label><input required type="date" name="date"></div><div class="field"><label>Time window</label><input required type="time" name="time"></div></div><div class="form-actions"><button class="button" type="button" data-modal-close>Cancel</button><button class="button button-primary" type="submit">Add request</button></div></form></section>
@endsection
