<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Apply as a Logistics Partner | Bearly Marketplace</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">@vite(['resources/css/logistics.css','resources/js/logistics.js'])</head>
<body class="registration-body" data-module="logistics">
<main class="registration-shell">
    <a class="registration-brand" href="{{ route('logistics.landing') }}"><img src="{{ asset('images/bearly-logo.png') }}" alt="Bearly Marketplace"><span><strong>Bearly Marketplace</strong><br><small>Logistics partner application</small></span></a>
    @if(session('registration_pending') || session('logistics_application'))
    <section class="registration-card" style="display:block"><div class="pending-state"><span class="metric-icon"><i data-lucide="clock-3"></i></span><p class="page-kicker">Application submitted</p><h2>Pending Administrator Approval</h2><p>Your Logistics partner application has been received. Bearly Admin will review your identity and business documents before your dashboard access is activated.</p><div class="detail-list" style="max-width:560px;margin:22px auto;text-align:left"><div class="detail-item"><small>Business</small><strong>{{ session('logistics_application.business_name','Submitted logistics facility') }}</strong></div><div class="detail-item"><small>Status</small><strong>Pending Administrator Approval</strong></div></div><a class="button button-primary" href="{{ route('login') }}">Return to main login</a></div></section>
    @else
    <section class="registration-card">
        <aside class="registration-aside"><span class="status-badge is-warning">Partner onboarding</span><h1>Operate a Bearly sorting center</h1><p>Complete the application below. Your account remains locked until Bearly Admin approves the submitted credentials.</p><div class="step-list"><div class="step-marker is-active" data-step-marker="1"><span>1</span><span><strong>Representative</strong><small>Personal details</small></span></div><div class="step-marker" data-step-marker="2"><span>2</span><span><strong>Facility</strong><small>Address and business</small></span></div><div class="step-marker" data-step-marker="3"><span>3</span><span><strong>Documents</strong><small>Identity and permit</small></span></div></div></aside>
        <div class="registration-main"><h2>Logistics application</h2><p>All required fields must be completed before submission.</p>
            @if($errors->any())<div class="flash-banner is-danger"><i data-lucide="circle-alert"></i><span>{{ $errors->first() }}</span></div>@endif
            <form action="{{ route('logistics.register.submit') }}" method="POST" enctype="multipart/form-data" data-registration-form>@csrf
                <section class="form-step" data-form-step="1"><div class="field-grid three"><div class="field"><label>First name <span>*</span></label><input name="first_name" value="{{ old('first_name') }}" required></div><div class="field"><label>Middle initial</label><input name="middle_initial" maxlength="5" value="{{ old('middle_initial') }}"></div><div class="field"><label>Last name <span>*</span></label><input name="last_name" value="{{ old('last_name') }}" required></div><div class="field"><label>Sex <span>*</span></label><select name="sex" required><option value="">Select</option>@foreach(['Male','Female','Prefer not to say'] as $sex)<option @selected(old('sex')===$sex)>{{ $sex }}</option>@endforeach</select></div><div class="field"><label>Birthday <span>*</span></label><input type="date" name="birthday" max="{{ now()->subDay()->format('Y-m-d') }}" value="{{ old('birthday') }}" required></div><div class="field"><label>Age</label><input data-age readonly placeholder="Calculated automatically"></div><div class="field"><label>Email address <span>*</span></label><input type="email" name="email" value="{{ old('email') }}" required></div><div class="field"><label>Contact number <span>*</span></label><input name="contact_number" value="{{ old('contact_number') }}" pattern="[0-9+() -]{7,20}" required></div></div><div class="form-actions"><a class="button" href="{{ route('logistics.landing') }}">Cancel</a><button class="button button-primary" type="button" data-step-next>Continue to facility</button></div></section>
                <section class="form-step" data-form-step="2" hidden><div class="field-grid"><div class="field span-2"><label>Business / sorting facility name <span>*</span></label><input name="business_name" value="{{ old('business_name') }}" required></div><div class="field"><label>Province <span>*</span></label><select name="province" data-province required><option value="">Loading provinces…</option></select></div><div class="field"><label>Municipality / City <span>*</span></label><select name="municipality" data-city required disabled><option value="">Select province first</option></select></div><div class="field"><label>Barangay <span>*</span></label><select name="barangay" data-barangay required disabled><option value="">Select city first</option></select></div><div class="field"><label>Street <span>*</span></label><input name="street" value="{{ old('street') }}" required></div><div class="field"><label>House / Building number <span>*</span></label><input name="house_number" value="{{ old('house_number') }}" required></div></div><div class="form-actions"><button class="button" type="button" data-step-back>Back</button><button class="button button-primary" type="button" data-step-next>Continue to documents</button></div></section>
                <section class="form-step" data-form-step="3" hidden><div class="field-grid"><div class="field"><label>Valid government ID <span>*</span></label><label class="upload-field"><input type="file" name="valid_id" accept=".jpg,.jpeg,.png,.pdf" required><i data-lucide="upload-cloud"></i><strong>Upload a valid ID</strong><small data-file-name>Choose a JPG, PNG, or PDF up to 5 MB</small></label></div><div class="field"><label>Business / DTI permit <span>*</span></label><label class="upload-field"><input type="file" name="business_permit" accept=".jpg,.jpeg,.png,.pdf" required><i data-lucide="file-check-2"></i><strong>Upload business permit</strong><small data-file-name>Choose a JPG, PNG, or PDF up to 5 MB</small></label></div></div><label class="toggle-row"><span class="toggle-copy"><strong>I certify that the submitted details are accurate.</strong><small>This preview demonstrates the Admin approval workflow.</small></span><span class="switch"><input type="checkbox" required><span></span></span></label><div class="form-actions"><button class="button" type="button" data-step-back>Back</button><button class="button button-primary" type="submit"><i data-lucide="send"></i>Submit application</button></div></section>
            </form>
        </div>
    </section>
    @endif
</main>
<div class="toast-stack" data-toast-stack></div><script src="https://unpkg.com/lucide@latest"></script>
</body></html>
