@extends('layouts.logistics')
@section('title','Rider Management')
@section('page-title','Rider Management')
@section('content')
<div class="page-header"><div><p class="page-kicker">Workforce</p><h2>Riders and courier applications</h2><p>Review applicants, verify credentials, and control access for approved rider accounts.</p></div><div class="page-actions"><button class="button" type="button" data-modal-open="invite-rider"><i data-lucide="user-plus"></i>Invite rider</button></div></div>
<div data-tab-scope>
    <div class="tabs" data-tabs><button class="tab-button is-active" type="button" data-tab="applications">Applications ({{ count($applications) }})</button><button class="tab-button" type="button" data-tab="accounts">Rider accounts ({{ count($riders) }})</button></div>
    <section class="panel" data-tab-panel="applications" style="margin-top:16px" data-table-scope>
        <div class="table-toolbar"><div class="search-field"><i data-lucide="search"></i><input type="search" data-table-search placeholder="Search applicant, ID, vehicle, or area"></div><select class="filter-select" data-filter-status><option value="">All statuses</option><option>Pending</option><option>Needs Review</option><option>Approved</option><option>Disapproved</option></select></div>
        <div class="table-wrap"><table class="data-table"><thead><tr><th data-sort>Application</th><th data-sort>Applicant</th><th>Vehicle</th><th>Preferred area</th><th data-sort>Submitted</th><th>Status</th><th>Actions</th></tr></thead><tbody>
        @foreach($applications as $application)
            <tr data-row data-record-row data-record-type="riderApplications" data-record-id="{{ $application['id'] }}" data-status="{{ $application['status'] }}">
                <td><strong>{{ $application['id'] }}</strong></td><td><span class="cell-title"><strong>{{ $application['name'] }}</strong><small>License and identity documents attached</small></span></td><td><span class="cell-title"><strong>{{ $application['vehicle'] }}</strong><small>{{ $application['plate'] }}</small></span></td><td>{{ $application['area'] }}</td><td>{{ $application['submitted'] }}</td><td><span class="status-badge" data-status-badge data-status="{{ $application['status'] }}">{{ $application['status'] }}</span></td>
                <td><div class="row-actions"><button class="button button-small" type="button" data-modal-open="review-{{ $application['id'] }}">Review</button><button class="button button-small button-primary" type="button" data-set-status="Approved" data-success="{{ $application['name'] }} approved as a rider.">Approve</button></div></td>
            </tr>
        @endforeach
        <tr><td class="empty-row" colspan="7" data-empty-row>No rider applications match these filters.</td></tr>
        </tbody></table></div>
    </section>
    <section class="panel" data-tab-panel="accounts" hidden style="margin-top:16px" data-table-scope>
        <div class="table-toolbar"><div class="search-field"><i data-lucide="search"></i><input type="search" data-table-search placeholder="Search rider, vehicle, or zone"></div><select class="filter-select" data-filter-status><option value="">All account states</option><option>Active</option><option>Inactive</option></select></div>
        <div class="table-wrap"><table class="data-table"><thead><tr><th>Rider</th><th>Vehicle</th><th>Assigned zone</th><th>Completed jobs</th><th>Rating</th><th>Account</th><th>Actions</th></tr></thead><tbody>
        @foreach($riders as $rider)<tr data-row data-record-row data-record-type="riderAccounts" data-record-id="{{ $rider['name'] }}" data-status="{{ $rider['status'] }}"><td><strong>{{ $rider['name'] }}</strong></td><td>{{ $rider['vehicle'] }}</td><td>{{ $rider['zone'] }}</td><td>{{ $rider['jobs'] }}</td><td>★ {{ $rider['rating'] }}</td><td><span class="status-badge" data-status-badge data-status="{{ $rider['status'] }}">{{ $rider['status'] }}</span></td><td><button class="button button-small" type="button" data-toggle-record>{{ $rider['status'] === 'Active' ? 'Deactivate' : 'Activate' }}</button></td></tr>@endforeach
        <tr><td class="empty-row" colspan="7" data-empty-row>No rider accounts match these filters.</td></tr></tbody></table></div>
    </section>
</div>
@foreach($applications as $application)
<section class="modal" data-modal="review-{{ $application['id'] }}" hidden><div class="modal-header"><div><h3>Review {{ $application['id'] }}</h3><p>Verify the applicant and submitted documents.</p></div><button class="icon-button" type="button" data-modal-close><i data-lucide="x"></i></button></div><div class="modal-body"><div class="detail-list"><div class="detail-item"><small>Applicant</small><strong>{{ $application['name'] }}</strong></div><div class="detail-item"><small>Preferred area</small><strong>{{ $application['area'] }}</strong></div><div class="detail-item"><small>Vehicle</small><strong>{{ $application['vehicle'] }} · {{ $application['plate'] }}</strong></div><div class="detail-item"><small>Submitted</small><strong>{{ $application['submitted'] }}</strong></div><div class="detail-item"><small>Driver’s license</small><strong>Verified preview document</strong></div><div class="detail-item"><small>Vehicle registration</small><strong>Verified preview document</strong></div></div></div><div class="modal-footer"><button class="button button-danger" type="button" data-set-status="Disapproved" data-success="Application disapproved.">Disapprove</button><button class="button button-primary" type="button" data-set-status="Approved" data-success="{{ $application['name'] }} approved as a rider.">Approve application</button></div></section>
@endforeach
<section class="modal" data-modal="invite-rider" hidden><div class="modal-header"><div><h3>Invite a rider</h3><p>Generate a preview invitation for a prospective courier.</p></div><button class="icon-button" type="button" data-modal-close><i data-lucide="x"></i></button></div><form class="modal-body" data-preview-form="riderInvitation" data-success="Rider invitation prepared."><div class="field-grid"><div class="field"><label>Full name</label><input name="name" required></div><div class="field"><label>Email address</label><input type="email" name="email" required></div><div class="field span-2"><label>Preferred area</label><select name="area" required><option value="">Select area</option><option>San Pablo North</option><option>San Pablo South</option><option>Calauan / Bay</option><option>Pila / Sta. Cruz</option></select></div></div><div class="form-actions"><button class="button" type="button" data-modal-close>Cancel</button><button class="button button-primary" type="submit">Prepare invitation</button></div></form></section>
@endsection
