@extends('layouts.logistics')
@section('title','Rider Management') @section('page-title','Rider Management')
@section('content')
<div class="page-intro"><div><span class="eyebrow">Rider Operations</span><h2>Applications & Rider Accounts</h2><p>Review credentials, approve or disapprove incoming rider applications, and activate or deactivate existing accounts.</p></div></div>
<section class="card" style="margin-bottom:16px"><div class="card-head"><h3>Incoming applications</h3><input class="field" placeholder="Search applications..." data-filter="rider-apps"></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Application</th><th>Rider</th><th>Vehicle</th><th>Area</th><th>Submitted</th><th>Status</th><th>Action</th></tr></thead><tbody>
@foreach($applications as $a)<tr data-state-row="{{ $a['id'] }}" data-filter-row="rider-apps"><td class="table-title">{{ $a['id'] }}</td><td>{{ $a['name'] }}<span class="table-sub">{{ $a['plate'] }}</span></td><td>{{ $a['vehicle'] }}</td><td>{{ $a['area'] }}</td><td>{{ $a['submitted'] }}</td><td><span data-state-badge class="badge {{ $a['status']==='Pending'?'badge-warning':'badge-info' }}">{{ $a['status'] }}</span></td><td><div class="actions"><button class="btn btn-success" data-status-action="Approved">Approve</button><button class="btn btn-danger" data-status-action="Disapproved">Disapprove</button><button class="btn btn-soft" data-mock-action="Credential preview opened for {{ $a['name'] }}.">Credentials</button></div></td></tr>@endforeach
</tbody></table></div></section>
<section class="card"><div class="card-head"><h3>Existing rider accounts</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Rider</th><th>Vehicle</th><th>Zone</th><th>Jobs</th><th>Rating</th><th>Status</th><th>Control</th></tr></thead><tbody>@foreach($riders as $r)<tr data-state-row="{{ $r['name'] }}"><td class="table-title">{{ $r['name'] }}</td><td>{{ $r['vehicle'] }}</td><td>{{ $r['zone'] }}</td><td>{{ $r['jobs'] }}</td><td>{{ $r['rating'] }}</td><td><span data-state-badge class="badge {{ $r['status']==='Active'?'badge-success':'badge-neutral' }}">{{ $r['status'] }}</span></td><td><div class="actions"><button class="btn btn-success" data-status-action="Active">Activate</button><button class="btn btn-danger" data-status-action="Inactive">Deactivate</button></div></td></tr>@endforeach</tbody></table></div></section>
@endsection
