@extends('layouts.logistics')
@section('title','Sorting Center')
@section('page-title','Sorting Center')
@section('content')
<div class="page-header"><div><p class="page-kicker">Parcel routing</p><h2>Sort parcels by delivery zone</h2><p>Validate destinations, group packages, and flag exceptions before dispatch assignment.</p></div><div class="page-actions"><a class="button" href="{{ route('logistics.incoming') }}"><i data-lucide="package-open"></i>View intake ledger</a><button class="button button-primary" type="button" data-modal-open="batch-sort"><i data-lucide="layers-3"></i>Batch sort</button></div></div>
<section class="metric-strip"><article class="metric-item"><span class="metric-icon"><i data-lucide="inbox"></i></span><span class="metric-copy"><small>Unsorted queue</small><strong>39</strong><span>Oldest waiting 18 minutes</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="circle-check-big"></i></span><span class="metric-copy"><small>Sorted today</small><strong>107</strong><span>73% of intake</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="map"></i></span><span class="metric-copy"><small>Active zones</small><strong>5</strong><span>All areas staffed</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="triangle-alert"></i></span><span class="metric-copy"><small>Exceptions</small><strong>1</strong><span>Destination review needed</span></span></article></section>
<section class="panel" data-table-scope>
    <div class="table-toolbar"><div class="search-field"><i data-lucide="search"></i><input type="search" data-table-search placeholder="Search waybill, seller, or destination"></div><select class="filter-select" data-filter-status><option value="">All statuses</option><option>Received</option><option>Sorted</option><option>Exception</option></select><select class="filter-select" data-filter-zone><option value="">All zones</option><option>SP-N1</option><option>SP-N2</option><option>SP-S2</option><option>PILA-1</option><option>CAL-1</option><option>STC-2</option></select></div>
    <div class="table-wrap"><table class="data-table"><thead><tr><th data-sort>Waybill</th><th>Seller</th><th>Destination</th><th>Package</th><th>Assign zone</th><th>Status</th><th>Action</th></tr></thead><tbody>
    @foreach($parcels as $parcel)<tr data-row data-record-row data-record-type="sorting" data-record-id="{{ $parcel['waybill'] }}" data-status="{{ $parcel['status'] }}" data-zone="{{ $parcel['zone'] }}"><td><strong>{{ $parcel['waybill'] }}</strong></td><td>{{ $parcel['seller'] }}</td><td>{{ $parcel['destination'] }}</td><td>{{ $parcel['size'] }}</td><td><select class="filter-select" data-zone-select aria-label="Zone for {{ $parcel['waybill'] }}"><option value="">Select zone</option>@foreach(['SP-N1','SP-N2','SP-S2','PILA-1','CAL-1','STC-2'] as $zone)<option value="{{ $zone }}" @selected($parcel['zone']===$zone)>{{ $zone }}</option>@endforeach</select></td><td><span class="status-badge" data-status-badge data-status="{{ $parcel['status'] }}">{{ $parcel['status'] }}</span></td><td><div class="row-actions"><button class="button button-small button-primary" type="button" data-sort-parcel>Mark sorted</button><button class="button button-small" type="button" data-set-status="Exception">Flag</button></div></td></tr>@endforeach
    <tr><td class="empty-row" colspan="7" data-empty-row>No parcels match these filters.</td></tr></tbody></table></div>
</section>
<section class="modal" data-modal="batch-sort" hidden><div class="modal-header"><div><h3>Batch sort parcels</h3><p>Apply one destination zone to a scanned parcel group.</p></div><button class="icon-button" type="button" data-modal-close><i data-lucide="x"></i></button></div><form class="modal-body" data-preview-form="batchSort" data-success="Batch sorting preview saved."><div class="field"><label>Scan or paste waybill numbers</label><textarea required name="waybills" placeholder="One waybill per line"></textarea></div><div class="field" style="margin-top:14px"><label>Destination zone</label><select required name="zone"><option value="">Select zone</option><option>SP-N1</option><option>SP-N2</option><option>SP-S2</option><option>PILA-1</option><option>CAL-1</option><option>STC-2</option></select></div><div class="form-actions"><button class="button" type="button" data-modal-close>Cancel</button><button class="button button-primary" type="submit">Apply zone</button></div></form></section>
@endsection
