<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><meta name="csrf-token" content="{{ csrf_token() }}">
<title>@yield('title', 'Rider Center') | Bearly</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet">
@vite(['resources/css/rider.css','resources/js/rider.js'])</head>
<body class="ops-body" data-module="rider"><div class="ops-shell"><aside class="ops-sidebar">
<div class="ops-sidebar-header"><button class="ops-menu-button" type="button" data-menu><i class="ui-icon" data-lucide="menu"></i></button><a href="{{ route('rider.dashboard.deliveries') }}" class="ops-brand"><img src="{{ asset('images/bearly-logo.png') }}" alt="Bearly"><small>Rider Center</small></a></div>
<nav class="ops-nav"><div class="ops-nav-label">Workspace</div><a href="{{ route('rider.dashboard.pickups') }}" class="ops-nav-link {{ request()->routeIs('rider.dashboard.pickups') ? 'is-active' : '' }}"><i class="ui-icon" data-lucide="package-plus"></i><span>Pickup Jobs</span></a>
<a href="{{ route('rider.dashboard.deliveries') }}" class="ops-nav-link {{ request()->routeIs('rider.dashboard.deliveries') ? 'is-active' : '' }}"><i class="ui-icon" data-lucide="bike"></i><span>Deliveries</span></a>
<a href="{{ route('rider.earnings') }}" class="ops-nav-link {{ request()->routeIs('rider.earnings') ? 'is-active' : '' }}"><i class="ui-icon" data-lucide="wallet-cards"></i><span>Earnings</span></a>
<a href="{{ route('rider.history') }}" class="ops-nav-link {{ request()->routeIs('rider.history') ? 'is-active' : '' }}"><i class="ui-icon" data-lucide="history"></i><span>Delivery History</span></a>
<a href="{{ route('rider.messages') }}" class="ops-nav-link {{ request()->routeIs('rider.messages') ? 'is-active' : '' }}"><i class="ui-icon" data-lucide="message-circle"></i><span>Messages</span></a>
<a href="{{ route('rider.account') }}" class="ops-nav-link {{ request()->routeIs('rider.account') ? 'is-active' : '' }}"><i class="ui-icon" data-lucide="user-round-cog"></i><span>Account</span></a></nav>
<div class="ops-sidebar-footer"><a href="{{ route('login') }}" class="ops-nav-link ops-logout"><i class="ui-icon" data-lucide="log-out"></i><span>Logout</span></a></div></aside>
<button class="ops-overlay" type="button" data-overlay></button><div class="ops-main"><header class="ops-topbar"><div class="ops-topbar-left"><button class="icon-button mobile-menu" type="button" data-mobile-menu><i class="ui-icon" data-lucide="menu"></i></button><h1>@yield('page-title','Rider Center')</h1></div>
<div class="ops-topbar-actions"><div class="popover-wrap"><button class="icon-button notification-trigger" data-popover-toggle="notifications"><i class="ui-icon" data-lucide="bell"></i>@if(count($topNotifications ?? []))<span class="notification-dot"></span>@endif</button>
<div class="topbar-popover" data-popover="notifications" hidden><div class="popover-heading"><strong>Notifications</strong></div>@forelse($topNotifications ?? [] as $n)<button class="notification-row"><span><strong>{{ $n['title'] }}</strong><small>{{ $n['time'] }}</small></span></button>@empty<div class="card-body">No notifications.</div>@endforelse</div></div>
<div class="popover-wrap"><button class="profile-button" data-popover-toggle="profile"><span class="avatar">{{ $rider['initials'] ?? 'BR' }}</span><span class="profile-copy"><strong>{{ $rider['name'] ?? 'Bearly User' }}</strong><small>{{ $rider['role'] ?? 'Rider Center' }}</small></span><i class="ui-icon" data-lucide="chevron-down"></i></button>
<div class="topbar-popover profile-popover" data-popover="profile" hidden><a href="{{ route('rider.account') }}"><i data-lucide="user-round-cog"></i>Account settings</a><a href="{{ route('login') }}"><i data-lucide="log-out"></i>Logout</a></div></div></div></header>
<main class="ops-content">@yield('content')</main></div></div><div class="toast-stack" data-toast-stack></div><script src="https://unpkg.com/lucide@latest"></script></body></html>