@extends('layouts.admin')
@section('title','Fulfillment Monitoring')
@section('page-title','Fulfillment Monitoring')
@section('content')
<section class="page-hero"><div><span class="eyebrow">Logistics monitoring</span><h1>Shipment and dispatch overview</h1><p>Track live waybills, parcels, shipment events, delivery outcomes, and administrative overrides.</p></div></section>
<section class="kpi-grid kpi-grid-compact">@foreach(['pending_pickup'=>'Pending pickup','intake'=>'Sorting intake','transit'=>'In transit','delivered'=>'Delivered','failed'=>'Failures / exceptions'] as $key=>$label)<article class="mini-stat"><span><i data-lucide="package"></i></span><div><strong>{{ $metrics[$key] }}</strong><small>{{ $label }}</small></div></article>@endforeach</section>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">Fulfillment ledger</span><h2>Tracked shipments</h2></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Shipment / Waybill</th><th>Order / Seller</th><th>Buyer</th><th>Parcels</th><th>Status</th><th>Last event</th><th class="align-right">Inspect</th></tr></thead><tbody>
@forelse($shipments as $shipment)<tr><td><strong>{{ $shipment->shipment_no }}</strong><small class="table-subline">{{ $shipment->waybill?->waybill_no ?? 'Waybill pending' }}</small></td><td>{{ $shipment->sellerOrder->order->order_no }} · {{ $shipment->sellerOrder->store->name }}</td><td>{{ $shipment->sellerOrder->order->buyer->name }}</td><td>{{ $shipment->parcels->count() }}</td><td><span class="status-badge badge-info">{{ str($shipment->status)->replace('_',' ')->title() }}</span></td><td>{{ $shipment->events->last()?->occurred_at?->format('M j, g:i A') ?? '—' }}</td><td class="align-right"><button type="button" class="button button-ghost button-small" data-open-modal="shipment-{{ $shipment->id }}"><i data-lucide="eye"></i> View</button></td></tr>@empty<tr><td colspan="7"><div class="table-empty"><i data-lucide="package-open"></i><strong>No shipments yet</strong><span>Fulfillment records will appear after seller handoff.</span></div></td></tr>@endforelse
</tbody></table></div></section>{{ $shipments->links() }}
@foreach($shipments as $shipment)<div class="modal-shell" data-modal="shipment-{{ $shipment->id }}" hidden><button type="button" class="modal-backdrop" data-close-modal></button><section class="modal-card modal-wide" role="dialog" aria-modal="true"><div class="modal-heading"><div><span class="eyebrow">{{ $shipment->shipment_no }}</span><h2>Waybill and delivery history</h2></div><button type="button" class="icon-button" data-close-modal><i data-lucide="x"></i></button></div><div class="review-details"><div class="detail-note"><span>Waybill</span><p>{{ $shipment->waybill?->waybill_no ?? 'Not generated' }} · {{ $shipment->waybill?->piece_count ?? 0 }} piece(s)<br>{{ $shipment->parcels->pluck('parcel_no')->implode(', ') ?: 'No parcels' }}</p></div><div class="detail-note"><span>Shipment events</span><p>@forelse($shipment->events as $event){{ $event->occurred_at?->format('M j, g:i A') }} — {{ str($event->to_status)->replace('_',' ')->title() }}@if($event->notes) · {{ $event->notes }}@endif @if(!$loop->last)<br>@endif @empty No events recorded. @endforelse</p></div><form method="POST" action="{{ route('admin.fulfillment.override',$shipment) }}">@csrf @method('PATCH')<label class="form-field"><span>Override status</span><select name="status" required>@foreach(['pending_waybill','ready_for_pickup','at_sorting_center','in_transit','out_for_delivery','delivered','delivery_failed','exception'] as $status)<option value="{{ $status }}" @selected($shipment->status===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select></label><label class="form-field"><span>Reason</span><textarea name="note" rows="3" required></textarea></label><div class="modal-footer"><button class="button button-danger-soft" type="submit">Apply audited override</button></div></form></div></section></div>@endforeach
@endsection
