@extends('rider.layouts.app')
@section('title','Items for Delivery')
@section('page-title','Items for Delivery')
@section('content')
<div class="page-header"><div><p class="page-kicker">Active delivery route</p><h2>Customer delivery assignments</h2><p>Prioritize today’s stops, verify payment requirements, and complete each customer handoff.</p></div><div class="page-actions"><span class="rider-availability">Route active</span><a class="button" href="{{ route('rider.dashboard.pickups') }}"><i data-lucide="package-plus"></i>Available pickups</a></div></div>
<section class="metric-strip"><article class="metric-item"><span class="metric-icon"><i data-lucide="package"></i></span><span class="metric-copy"><small>Assigned parcels</small><strong>3</strong><span>All within SP-N1</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="bike"></i></span><span class="metric-copy"><small>Out for delivery</small><strong>1</strong><span>Next stop in 14 minutes</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="banknote"></i></span><span class="metric-copy"><small>COD to collect</small><strong>₱1,970</strong><span>Across 2 customer stops</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="wallet"></i></span><span class="metric-copy"><small>Route earnings</small><strong>₱210</strong><span>Projected after completion</span></span></article></section>
<section class="panel" data-table-scope><div class="panel-header"><div><h3>Delivery route</h3><p>System assignments released by Laguna Central Logistics.</p></div><button class="button button-small" type="button" data-optimize-route><i data-lucide="route"></i>Optimize order</button></div><div class="table-toolbar"><div class="search-field"><i data-lucide="search"></i><input type="search" data-table-search placeholder="Search customer, waybill, address, or zone"></div><select class="filter-select" data-filter-status><option value="">All delivery stages</option><option>Assigned</option><option>In Transit</option><option>Delivered</option></select></div><div class="panel-body"><div class="job-grid">
@foreach($deliveries as $delivery)<article class="job-card" data-row data-record-row data-record-type="deliveryJobs" data-record-id="{{ $delivery['id'] }}" data-status="{{ $delivery['status'] }}"><div class="job-card-head"><div><h3>{{ $delivery['customer'] }}</h3><small>{{ $delivery['id'] }} · {{ $delivery['waybill'] }}</small></div><span class="status-badge" data-status-badge data-status="{{ $delivery['status'] }}">{{ $delivery['status'] }}</span></div><div class="job-card-body"><div class="job-detail"><i data-lucide="map-pin"></i><span>{{ $delivery['address'] }}<small>Zone {{ $delivery['zone'] }}</small></span></div><div class="job-detail"><i data-lucide="receipt"></i><span>{{ $delivery['cod'] }}<small>{{ $delivery['cod']==='Paid'?'Prepaid order':'Collect upon handoff' }}</small></span></div><div class="job-detail"><i data-lucide="navigation"></i><span>{{ $loop->first?'Next route stop':'Queued stop '.$loop->iteration }}<small>System delivery assignment</small></span></div></div><div class="job-card-footer"><a class="button button-primary" href="{{ route('rider.orders.delivery',$delivery['id']) }}">Open delivery</a></div></article>@endforeach
</div><p class="empty-copy" data-empty-cards hidden>No deliveries match the selected filters.</p></div></section>
<div class="content-grid equal" style="margin-top:20px"><section class="panel"><div class="panel-header"><div><h3>Available pickup requests</h3><p>Optional jobs near your delivery route.</p></div><a class="text-button" href="{{ route('rider.dashboard.pickups') }}">View queue</a></div><div class="panel-body attention-list">@foreach($availablePickups as $pickup)<a class="attention-item" href="{{ route('rider.dashboard.pickups') }}"><i data-lucide="package-plus"></i><span><strong>{{ $pickup['seller'] }} · {{ $pickup['parcels'] }} parcels</strong><small>{{ $pickup['area'] }} · {{ $pickup['distance'] }}</small></span><i data-lucide="chevron-right"></i></a>@endforeach</div></section><section class="panel"><div class="panel-header"><div><h3>Route checklist</h3><p>Before leaving the sorting center.</p></div></div><div class="panel-body">@foreach(['All waybills scanned','COD amounts verified','Phone is charged and online','Dispatch manifest acknowledged'] as $item)<label class="toggle-row"><span class="toggle-copy"><strong>{{ $item }}</strong></span><span class="switch"><input type="checkbox"><span></span></span></label>@endforeach</div></section></div>
@endsection
