@extends('rider.layouts.app')
@section('title','Items for Pickup')
@section('page-title','Items for Pickup')
@section('content')
<div class="page-header"><div><p class="page-kicker">Rider pickup queue</p><h2>Seller parcels ready for collection</h2><p>Review pickup alerts, accept nearby requests, and begin assigned seller pickups.</p></div><div class="page-actions"><span class="rider-availability">Available for jobs</span><button class="button" type="button" data-refresh-preview><i data-lucide="refresh-cw"></i>Refresh queue</button></div></div>
<section class="metric-strip"><article class="metric-item"><span class="metric-icon"><i data-lucide="package-check"></i></span><span class="metric-copy"><small>Assigned pickup</small><strong>1</strong><span>Next window at 2:30 PM</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="radar"></i></span><span class="metric-copy"><small>Available nearby</small><strong>2</strong><span>Within a 6 km radius</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="boxes"></i></span><span class="metric-copy"><small>Expected parcels</small><strong>13</strong><span>Across all pickup jobs</span></span></article><article class="metric-item"><span class="metric-icon"><i data-lucide="wallet"></i></span><span class="metric-copy"><small>Potential earnings</small><strong>₱150</strong><span>If all jobs are completed</span></span></article></section>
<div class="content-grid" style="margin-bottom:20px"><section class="panel"><div class="panel-header"><div><h3>Real-time pickup alerts</h3><p>Latest notices from Sellers and your assigned Logistics center.</p></div><span class="status-badge is-success">Live preview</span></div><div class="panel-body alert-feed">@foreach($alerts as $alert)<div class="alert-row"><span><i data-lucide="bell-ring"></i></span><span><strong>{{ $alert['title'] }}</strong><small>{{ $alert['detail'] }}</small></span><time>{{ $alert['time'] }}</time></div>@endforeach</div></section><aside class="panel"><div class="panel-header"><div><h3>Today’s pickup plan</h3><p>Capacity and return target.</p></div></div><div class="panel-body attention-list"><div class="attention-item"><i data-lucide="clock-3"></i><span><strong>2:30 PM first window</strong><small>TechVault PH · San Rafael</small></span></div><div class="attention-item"><i data-lucide="package"></i><span><strong>13 parcel capacity</strong><small>Motorcycle box has 18 slots</small></span></div><div class="attention-item"><i data-lucide="warehouse"></i><span><strong>Return to Intake Bay 2</strong><small>Before the 5:30 PM cutoff</small></span></div></div></aside></div>
<section class="panel" data-table-scope><div class="panel-header"><div><h3>Pickup opportunities</h3><p>Assigned and available seller collections.</p></div></div><div class="table-toolbar"><div class="search-field"><i data-lucide="search"></i><input type="search" data-table-search placeholder="Search seller, pickup ID, or location"></div><select class="filter-select" data-filter-status><option value="">All job states</option><option>Assigned</option><option>Available</option><option>Accepted</option></select></div><div class="panel-body"><div class="job-grid">
@foreach($pickups as $pickup)<article class="job-card" data-row data-record-row data-record-type="pickupJobs" data-record-id="{{ $pickup['id'] }}" data-status="{{ $pickup['status'] }}"><div class="job-card-head"><div><h3>{{ $pickup['seller'] }}</h3><small>{{ $pickup['id'] }}</small></div><span class="status-badge" data-status-badge data-status="{{ $pickup['status'] }}">{{ $pickup['status'] }}</span></div><div class="job-card-body"><div class="job-detail"><i data-lucide="map-pin"></i><span>{{ $pickup['address'] }}<small>{{ $pickup['distance'] }} from your current area</small></span></div><div class="job-detail"><i data-lucide="boxes"></i><span>{{ $pickup['parcels'] }} parcels<small>Seller reports all packages ready</small></span></div><div class="job-detail"><i data-lucide="clock"></i><span>{{ $pickup['window'] }}<small>Requested pickup window</small></span></div></div><div class="job-card-footer">@if($pickup['status']==='Assigned')<a class="button button-primary" href="{{ route('rider.orders.pickup',$pickup['id']) }}">Start pickup</a>@else<button class="button button-primary" type="button" data-accept-pickup>Accept job</button><button class="button" type="button" data-preview-detail>Details</button>@endif</div></article>@endforeach
</div><p class="empty-copy" data-empty-cards hidden>No pickup jobs match the selected filters.</p></div></section>
@endsection
