@extends('rider.layouts.app')
@section('title','Account')
@section('page-title','Account')
@section('content')
<div class="page-header"><div><p class="page-kicker">Profile and security</p><h2>Rider account management</h2><p>Maintain your personal details, registered vehicle, service address, and account security.</p></div></div>
<section class="panel" style="margin-bottom:18px"><div class="account-summary"><span class="avatar">{{ $rider['initials'] }}</span><div><h3>{{ $rider['name'] }}</h3><p>{{ $rider['role'] }} · {{ $rider['vehicle'] }} · {{ $rider['plate'] }}</p></div><span class="status-badge is-success" style="margin-left:auto">Verified rider</span></div></section>
<div data-tab-scope><div class="tabs" data-tabs><button class="tab-button is-active" type="button" data-tab="profile">Profile</button><button class="tab-button" type="button" data-tab="vehicle">Vehicle</button><button class="tab-button" type="button" data-tab="addresses">Manage Addresses</button><button class="tab-button" type="button" data-tab="security">Password & Security</button></div>
<section class="panel" data-tab-panel="profile" style="margin-top:16px"><div class="panel-header"><div><h3>Personal profile</h3><p>Information shared with Logistics dispatchers.</p></div></div><form class="panel-body" data-preview-form="profile"><div class="field-grid"><div class="field"><label>Full name</label><input name="name" value="{{ $rider['name'] }}" required></div><div class="field"><label>Sex</label><select name="sex"><option @selected($profile['sex']==='Male')>Male</option><option @selected($profile['sex']==='Female')>Female</option><option>Prefer not to say</option></select></div><div class="field"><label>Email address</label><input type="email" name="email" value="{{ $rider['email'] }}" required></div><div class="field"><label>Contact number</label><input name="contact" value="{{ $profile['contact'] }}" required></div><div class="field"><label>Birthday</label><input type="date" name="birthday" value="{{ $profile['birthday'] }}"></div><div class="field"><label>Emergency contact</label><input name="emergency_contact" value="{{ $profile['emergency_contact'] }}"></div></div><div class="form-actions"><button class="button button-primary" type="submit">Save profile</button></div></form></section>
<section class="panel" data-tab-panel="vehicle" hidden style="margin-top:16px"><div class="panel-header"><div><h3>Registered vehicle</h3><p>Used for capacity planning and rider assignment.</p></div><span class="status-badge is-success">Documents verified</span></div><form class="panel-body" data-preview-form="vehicle"><div class="field-grid"><div class="field"><label>Vehicle type</label><select name="vehicle"><option selected>{{ $rider['vehicle'] }}</option><option>Tricycle</option><option>E-bike</option><option>Van</option></select></div><div class="field"><label>Plate number</label><input name="plate" value="{{ $rider['plate'] }}" required></div><div class="field"><label>Vehicle model</label><input name="model" value="Honda Click 125i"></div><div class="field"><label>Parcel capacity</label><input type="number" name="capacity" value="18"></div></div><div class="form-actions"><button class="button button-primary" type="submit">Save vehicle details</button></div></form></section>
<section class="panel" data-tab-panel="addresses" hidden style="margin-top:16px"><div class="panel-header"><div><h3>Saved addresses</h3><p>Your home and preferred service areas.</p></div><button class="button button-small button-primary" type="button" data-modal-open="add-address"><i data-lucide="plus"></i>Add address</button></div><div class="panel-body"><div class="address-card"><span><i data-lucide="house"></i></span><span><strong>Home address</strong><small>{{ $profile['address'] }}</small></span><button class="button button-small" type="button" data-address-edit>Edit</button></div><div class="address-card"><span><i data-lucide="map-pinned"></i></span><span><strong>Preferred service area</strong><small>San Pablo North · SP-N1</small></span><button class="button button-small" type="button" data-address-edit>Edit</button></div></div></section>
<section class="panel" data-tab-panel="security" hidden style="margin-top:16px"><div class="panel-header"><div><h3>Change password</h3><p>Use at least eight characters.</p></div></div><form class="panel-body" data-password-form><div class="field-grid"><div class="field span-2"><label>Current password</label><input type="password" required></div><div class="field"><label>New password</label><input type="password" name="new_password" minlength="8" required></div><div class="field"><label>Confirm new password</label><input type="password" name="new_password_confirmation" minlength="8" required></div></div><div class="form-actions"><button class="button button-primary" type="submit">Validate password update</button></div></form></section></div>
<section class="modal" data-modal="add-address" hidden><div class="modal-header"><div><h3>Add rider address</h3><p>Save an additional address in this preview.</p></div><button class="icon-button" type="button" data-modal-close><i data-lucide="x"></i></button></div><form class="modal-body" data-preview-form="address"><div class="field-grid"><div class="field"><label>Address label</label><input name="label" required placeholder="e.g. Secondary home"></div><div class="field"><label>Province</label><input name="province" required value="Laguna"></div><div class="field"><label>Municipality / City</label><input name="city" required value="San Pablo City"></div><div class="field"><label>Barangay</label><input name="barangay" required></div><div class="field span-2"><label>Street / House number</label><input name="street" required></div></div><div class="form-actions"><button class="button" type="button" data-modal-close>Cancel</button><button class="button button-primary" type="submit">Save address</button></div></form></section>
@endsection
